//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLUESOFT;Initial Catalog=AGRICOLA2017;Integrated Security=True")]
        public string AGRICOLA2017ConnectionString1 {
            get {
                return ((string)(this["AGRICOLA2017ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLUESOFT;Initial Catalog=AGRICOLA2017;Integrated Security=True")]
        public string agricolasanjuan2014ConnectionString {
            get {
                return ((string)(this["agricolasanjuan2014ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLUESOFT;Initial Catalog=AGRICOLA2017;Integrated Security=True")]
        public string attBackupConnectionString {
            get {
                return ((string)(this["attBackupConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLUESOFT;Initial Catalog=AGRICOLA2017;Integrated Security=True")]
        public string agricolasanjuan2014ConnectionString1 {
            get {
                return ((string)(this["agricolasanjuan2014ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLUESOFT;Initial Catalog=AGRICOLA2017;Integrated Security=True")]
        public string agricolasanjuan2014ConnectionString2 {
            get {
                return ((string)(this["agricolasanjuan2014ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLUESOFT;Initial Catalog=AGRICOLA2017;Integrated Security=True")]
        public string agricolasanjuan2014ConnectionString3 {
            get {
                return ((string)(this["agricolasanjuan2014ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BLUESOFT;Initial Catalog=AGRICOLA2017;Integrated Security=True")]
        public string AGRICOLA2017ConnectionString {
            get {
                return ((string)(this["AGRICOLA2017ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=74.208.128.178;Initial Catalog=saturno;Persist Security Info=True;Use" +
            "r ID=vsatsaturno;Password=saturno#111")]
        public string saturnoConnectionString {
            get {
                return ((string)(this["saturnoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=BDO;Persist Security Info=True;User ID=" +
            "eaurazo;Password=J^G|T1jS")]
        public string BDOConnectionString {
            get {
                return ((string)(this["BDOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=SATURNO;Persist Security Info=True;User" +
            " ID=eaurazo; Password=J^G|T1jS")]
        public string SATURNOConnectionString1 {
            get {
                return ((string)(this["SATURNOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=NSFAJA;Persist Security Info=True;User " +
            "ID=sa;Password=usersql$$nisira")]
        public string NSFAJAConnectionString {
            get {
                return ((string)(this["NSFAJAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=SATURNO;Persist Security Info=True;User" +
            " ID=eaurazo; Password=J^G|T1jS")]
        public string SATURNOConnectionString2 {
            get {
                return ((string)(this["SATURNOConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=NSFAJA;User ID=eaurazo;Password=J^G|T1j" +
            "S")]
        public string NSFAJAConnectionString1 {
            get {
                return ((string)(this["NSFAJAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=NSFAJA;User ID=eaurazo; Password=J^G|T1" +
            "jS")]
        public string NSFAJAConnectionString2 {
            get {
                return ((string)(this["NSFAJAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=BoltCoorp;Persist Security Info=True;Us" +
            "er ID=eaurao;Password=J^G|T1jS")]
        public string BoltCoorpConnectionString {
            get {
                return ((string)(this["BoltCoorpConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=FENOLOGIAS;Persist Security Info=True;U" +
            "ser ID=eaurazo; Password=J^G|T1jS")]
        public string FENOLOGIASConnectionString {
            get {
                return ((string)(this["FENOLOGIASConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=SATURNO;Persist Security Info=True;User" +
            " ID=eaurazo; Password=J^G|T1jS")]
        public string SATURNOConnectionString3 {
            get {
                return ((string)(this["SATURNOConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=SATURNO;Persist Security Info=True;User" +
            " ID=eaurazo; Password=J^G|T1jS")]
        public string SATURNOConnectionString4 {
            get {
                return ((string)(this["SATURNOConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=SATURNO;User ID=eaurazo; Password=J^G|T" +
            "1jS")]
        public string SATURNOConnectionString5 {
            get {
                return ((string)(this["SATURNOConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=SATURNO;Persist Security Info=True;User" +
            " ID=eaurazo; Password=J^G|T1jS")]
        public string SATURNOConnectionString6 {
            get {
                return ((string)(this["SATURNOConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=NSFAJA;Persist Security Info=True;User " +
            "ID=eaurazo; Password=J^G|T1jS")]
        public string NSFAJAConnectionString3 {
            get {
                return ((string)(this["NSFAJAConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=NSFAJA;Persist Security Info=True;User " +
            "ID=eaurazo;Password=J^G|T1jS")]
        public string NSFAJAConnectionString4 {
            get {
                return ((string)(this["NSFAJAConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.140.7;Initial Catalog=SATURNO;Persist Security Info=True;User" +
            " ID=eaurazo;Password=J^G|T1jS")]
        public string SATURNOConnectionString7 {
            get {
                return ((string)(this["SATURNOConnectionString7"]));
            }
        }
    }
}
