#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SATURNO")]
	public partial class AlmacenModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AlmacenModelDataContext() : 
				base(global::Asistencia.Datos.Properties.Settings.Default.SATURNOConnectionString8, mappingSource)
		{
			OnCreated();
		}
		
		public AlmacenModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlmacenModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlmacenModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlmacenModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoEPP")]
		public ISingleResult<SAS_ListadoEPPResult> SAS_ListadoEPP()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SAS_ListadoEPPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_EnvioNotificacionesStockEPP")]
		public int SAS_EnvioNotificacionesStockEPP()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SAS_ListadoEPPResult
	{
		
		private string _EmpresaID;
		
		private string _Empresa;
		
		private string _SucursalID;
		
		private string _Sucursal;
		
		private string _AlmacenID;
		
		private string _Almacen;
		
		private string _ProductoId;
		
		private string _producto;
		
		private string _UM;
		
		private System.Nullable<decimal> _cantidadFactor;
		
		public SAS_ListadoEPPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpresaID", DbType="VarChar(3)")]
		public string EmpresaID
		{
			get
			{
				return this._EmpresaID;
			}
			set
			{
				if ((this._EmpresaID != value))
				{
					this._EmpresaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="VarChar(200)")]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this._Empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucursalID", DbType="VarChar(3)")]
		public string SucursalID
		{
			get
			{
				return this._SucursalID;
			}
			set
			{
				if ((this._SucursalID != value))
				{
					this._SucursalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sucursal", DbType="VarChar(200)")]
		public string Sucursal
		{
			get
			{
				return this._Sucursal;
			}
			set
			{
				if ((this._Sucursal != value))
				{
					this._Sucursal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlmacenID", DbType="VarChar(3)")]
		public string AlmacenID
		{
			get
			{
				return this._AlmacenID;
			}
			set
			{
				if ((this._AlmacenID != value))
				{
					this._AlmacenID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Almacen", DbType="VarChar(50)")]
		public string Almacen
		{
			get
			{
				return this._Almacen;
			}
			set
			{
				if ((this._Almacen != value))
				{
					this._Almacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoId", DbType="VarChar(20)")]
		public string ProductoId
		{
			get
			{
				return this._ProductoId;
			}
			set
			{
				if ((this._ProductoId != value))
				{
					this._ProductoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="VarChar(258)")]
		public string producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					this._producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UM", DbType="VarChar(4)")]
		public string UM
		{
			get
			{
				return this._UM;
			}
			set
			{
				if ((this._UM != value))
				{
					this._UM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidadFactor", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> cantidadFactor
		{
			get
			{
				return this._cantidadFactor;
			}
			set
			{
				if ((this._cantidadFactor != value))
				{
					this._cantidadFactor = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
