#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SATURNO")]
	public partial class BoltCoorpADDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProveedorITD(ProveedorITD instance);
    partial void UpdateProveedorITD(ProveedorITD instance);
    partial void DeleteProveedorITD(ProveedorITD instance);
    partial void InsertConsumidorFechaAplicacionC(ConsumidorFechaAplicacionC instance);
    partial void UpdateConsumidorFechaAplicacionC(ConsumidorFechaAplicacionC instance);
    partial void DeleteConsumidorFechaAplicacionC(ConsumidorFechaAplicacionC instance);
    partial void InsertusuarioMaquinaria(usuarioMaquinaria instance);
    partial void UpdateusuarioMaquinaria(usuarioMaquinaria instance);
    partial void DeleteusuarioMaquinaria(usuarioMaquinaria instance);
    #endregion
		
		public BoltCoorpADDataContext() : 
				base(global::Asistencia.Datos.Properties.Settings.Default.SATURNOConnectionString6, mappingSource)
		{
			OnCreated();
		}
		
		public BoltCoorpADDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoltCoorpADDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoltCoorpADDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoltCoorpADDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProveedorITD> ProveedorITD
		{
			get
			{
				return this.GetTable<ProveedorITD>();
			}
		}
		
		public System.Data.Linq.Table<ConsumidorFechaAplicacionC> ConsumidorFechaAplicacionC
		{
			get
			{
				return this.GetTable<ConsumidorFechaAplicacionC>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ListadoDeUsuariosDelSistema> SAS_ListadoDeUsuariosDelSistema
		{
			get
			{
				return this.GetTable<SAS_ListadoDeUsuariosDelSistema>();
			}
		}
		
		public System.Data.Linq.Table<usuarioMaquinaria> usuarioMaquinaria
		{
			get
			{
				return this.GetTable<usuarioMaquinaria>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ListadoCuentasBoltWeb> SAS_ListadoCuentasBoltWeb
		{
			get
			{
				return this.GetTable<SAS_ListadoCuentasBoltWeb>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ListadoAreaCuentaBolt> SAS_ListadoAreaCuentaBolt
		{
			get
			{
				return this.GetTable<SAS_ListadoAreaCuentaBolt>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ListadoPerfilCuentaBolt> SAS_ListadoPerfilCuentaBolt
		{
			get
			{
				return this.GetTable<SAS_ListadoPerfilCuentaBolt>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ListadoUsuariosNISIRAvsUsuarioBoltActivos> SAS_ListadoUsuariosNISIRAvsUsuarioBoltActivos
		{
			get
			{
				return this.GetTable<SAS_ListadoUsuariosNISIRAvsUsuarioBoltActivos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ConsumidorFechaAplicacionCListadoPorAnio")]
		public ISingleResult<SAS_ConsumidorFechaAplicacionCListadoPorAnioResult> SAS_ConsumidorFechaAplicacionCListadoPorAnio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(4)")] string anio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), anio);
			return ((ISingleResult<SAS_ConsumidorFechaAplicacionCListadoPorAnioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProveedorITD")]
	public partial class ProveedorITD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EmpresaId;
		
		private string _IdClieprov;
		
		private string _RazonSocial;
		
		private string _Rubro;
		
		private System.Nullable<decimal> _NivelImportancia;
		
		private System.Nullable<decimal> _PasaFlujo;
		
		private System.Nullable<byte> _Estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpresaIdChanging(string value);
    partial void OnEmpresaIdChanged();
    partial void OnIdClieprovChanging(string value);
    partial void OnIdClieprovChanged();
    partial void OnRazonSocialChanging(string value);
    partial void OnRazonSocialChanged();
    partial void OnRubroChanging(string value);
    partial void OnRubroChanged();
    partial void OnNivelImportanciaChanging(System.Nullable<decimal> value);
    partial void OnNivelImportanciaChanged();
    partial void OnPasaFlujoChanging(System.Nullable<decimal> value);
    partial void OnPasaFlujoChanged();
    partial void OnEstadoChanging(System.Nullable<byte> value);
    partial void OnEstadoChanged();
    #endregion
		
		public ProveedorITD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpresaId", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EmpresaId
		{
			get
			{
				return this._EmpresaId;
			}
			set
			{
				if ((this._EmpresaId != value))
				{
					this.OnEmpresaIdChanging(value);
					this.SendPropertyChanging();
					this._EmpresaId = value;
					this.SendPropertyChanged("EmpresaId");
					this.OnEmpresaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClieprov", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdClieprov
		{
			get
			{
				return this._IdClieprov;
			}
			set
			{
				if ((this._IdClieprov != value))
				{
					this.OnIdClieprovChanging(value);
					this.SendPropertyChanging();
					this._IdClieprov = value;
					this.SendPropertyChanged("IdClieprov");
					this.OnIdClieprovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="NChar(200)")]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this.OnRazonSocialChanging(value);
					this.SendPropertyChanging();
					this._RazonSocial = value;
					this.SendPropertyChanged("RazonSocial");
					this.OnRazonSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rubro", DbType="VarChar(50)")]
		public string Rubro
		{
			get
			{
				return this._Rubro;
			}
			set
			{
				if ((this._Rubro != value))
				{
					this.OnRubroChanging(value);
					this.SendPropertyChanging();
					this._Rubro = value;
					this.SendPropertyChanged("Rubro");
					this.OnRubroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelImportancia", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> NivelImportancia
		{
			get
			{
				return this._NivelImportancia;
			}
			set
			{
				if ((this._NivelImportancia != value))
				{
					this.OnNivelImportanciaChanging(value);
					this.SendPropertyChanging();
					this._NivelImportancia = value;
					this.SendPropertyChanged("NivelImportancia");
					this.OnNivelImportanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasaFlujo", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> PasaFlujo
		{
			get
			{
				return this._PasaFlujo;
			}
			set
			{
				if ((this._PasaFlujo != value))
				{
					this.OnPasaFlujoChanging(value);
					this.SendPropertyChanging();
					this._PasaFlujo = value;
					this.SendPropertyChanged("PasaFlujo");
					this.OnPasaFlujoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt")]
		public System.Nullable<byte> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConsumidorFechaAplicacionC")]
	public partial class ConsumidorFechaAplicacionC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdEmpresa;
		
		private string _ConsumidorId;
		
		private string _SiembraId;
		
		private string _CampanaAgricolaId;
		
		private decimal _AnioCampaña;
		
		private System.Nullable<System.DateTime> _FechaAplicacionEnFormacion;
		
		private System.Nullable<System.DateTime> _FechaAplicacionEnProduccion;
		
		private char _TipoRegistro;
		
		private System.Nullable<byte> _Estado;
		
		private string _Observacion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmpresaChanging(string value);
    partial void OnIdEmpresaChanged();
    partial void OnConsumidorIdChanging(string value);
    partial void OnConsumidorIdChanged();
    partial void OnSiembraIdChanging(string value);
    partial void OnSiembraIdChanged();
    partial void OnCampanaAgricolaIdChanging(string value);
    partial void OnCampanaAgricolaIdChanged();
    partial void OnAnioCampañaChanging(decimal value);
    partial void OnAnioCampañaChanged();
    partial void OnFechaAplicacionEnFormacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAplicacionEnFormacionChanged();
    partial void OnFechaAplicacionEnProduccionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAplicacionEnProduccionChanged();
    partial void OnTipoRegistroChanging(char value);
    partial void OnTipoRegistroChanged();
    partial void OnEstadoChanging(System.Nullable<byte> value);
    partial void OnEstadoChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    #endregion
		
		public ConsumidorFechaAplicacionC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this.OnIdEmpresaChanging(value);
					this.SendPropertyChanging();
					this._IdEmpresa = value;
					this.SendPropertyChanged("IdEmpresa");
					this.OnIdEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumidorId", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ConsumidorId
		{
			get
			{
				return this._ConsumidorId;
			}
			set
			{
				if ((this._ConsumidorId != value))
				{
					this.OnConsumidorIdChanging(value);
					this.SendPropertyChanging();
					this._ConsumidorId = value;
					this.SendPropertyChanged("ConsumidorId");
					this.OnConsumidorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiembraId", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SiembraId
		{
			get
			{
				return this._SiembraId;
			}
			set
			{
				if ((this._SiembraId != value))
				{
					this.OnSiembraIdChanging(value);
					this.SendPropertyChanging();
					this._SiembraId = value;
					this.SendPropertyChanged("SiembraId");
					this.OnSiembraIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampanaAgricolaId", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CampanaAgricolaId
		{
			get
			{
				return this._CampanaAgricolaId;
			}
			set
			{
				if ((this._CampanaAgricolaId != value))
				{
					this.OnCampanaAgricolaIdChanging(value);
					this.SendPropertyChanging();
					this._CampanaAgricolaId = value;
					this.SendPropertyChanged("CampanaAgricolaId");
					this.OnCampanaAgricolaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioCampaña", DbType="Decimal(4,0) NOT NULL")]
		public decimal AnioCampaña
		{
			get
			{
				return this._AnioCampaña;
			}
			set
			{
				if ((this._AnioCampaña != value))
				{
					this.OnAnioCampañaChanging(value);
					this.SendPropertyChanging();
					this._AnioCampaña = value;
					this.SendPropertyChanged("AnioCampaña");
					this.OnAnioCampañaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionEnFormacion", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaAplicacionEnFormacion
		{
			get
			{
				return this._FechaAplicacionEnFormacion;
			}
			set
			{
				if ((this._FechaAplicacionEnFormacion != value))
				{
					this.OnFechaAplicacionEnFormacionChanging(value);
					this.SendPropertyChanging();
					this._FechaAplicacionEnFormacion = value;
					this.SendPropertyChanged("FechaAplicacionEnFormacion");
					this.OnFechaAplicacionEnFormacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionEnProduccion", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaAplicacionEnProduccion
		{
			get
			{
				return this._FechaAplicacionEnProduccion;
			}
			set
			{
				if ((this._FechaAplicacionEnProduccion != value))
				{
					this.OnFechaAplicacionEnProduccionChanging(value);
					this.SendPropertyChanging();
					this._FechaAplicacionEnProduccion = value;
					this.SendPropertyChanged("FechaAplicacionEnProduccion");
					this.OnFechaAplicacionEnProduccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRegistro", DbType="Char(1) NOT NULL")]
		public char TipoRegistro
		{
			get
			{
				return this._TipoRegistro;
			}
			set
			{
				if ((this._TipoRegistro != value))
				{
					this.OnTipoRegistroChanging(value);
					this.SendPropertyChanging();
					this._TipoRegistro = value;
					this.SendPropertyChanged("TipoRegistro");
					this.OnTipoRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt")]
		public System.Nullable<byte> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(200)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this.OnObservacionChanging(value);
					this.SendPropertyChanging();
					this._Observacion = value;
					this.SendPropertyChanged("Observacion");
					this.OnObservacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ListadoDeUsuariosDelSistema")]
	public partial class SAS_ListadoDeUsuariosDelSistema
	{
		
		private string _IdUsuario;
		
		private string _IdCodigoGeneral;
		
		private string _Password;
		
		private string _NombreCompleto;
		
		private string _idArea;
		
		private string _area;
		
		private string _email;
		
		private string _idestado;
		
		private string _estado;
		
		private string _sedeId;
		
		private string _sede;
		
		private string _nivelAccesoId;
		
		private string _nivelAcceso;
		
		private string _IDSUCURSAL;
		
		private string _SUCURSAL;
		
		private int _puerdaId;
		
		private string _puerta;
		
		private string _EmpresaID;
		
		private string _SituacionPlanilla;
		
		public SAS_ListadoDeUsuariosDelSistema()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCodigoGeneral", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IdCodigoGeneral
		{
			get
			{
				return this._IdCodigoGeneral;
			}
			set
			{
				if ((this._IdCodigoGeneral != value))
				{
					this._IdCodigoGeneral = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="VarChar(150)")]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this._NombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idArea", DbType="VarChar(50)")]
		public string idArea
		{
			get
			{
				return this._idArea;
			}
			set
			{
				if ((this._idArea != value))
				{
					this._idArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="VarChar(100)")]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this._area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(60)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idestado", DbType="Char(10)")]
		public string idestado
		{
			get
			{
				return this._idestado;
			}
			set
			{
				if ((this._idestado != value))
				{
					this._idestado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sedeId", DbType="VarChar(50)")]
		public string sedeId
		{
			get
			{
				return this._sedeId;
			}
			set
			{
				if ((this._sedeId != value))
				{
					this._sedeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sede", DbType="VarChar(70)")]
		public string sede
		{
			get
			{
				return this._sede;
			}
			set
			{
				if ((this._sede != value))
				{
					this._sede = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivelAccesoId", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string nivelAccesoId
		{
			get
			{
				return this._nivelAccesoId;
			}
			set
			{
				if ((this._nivelAccesoId != value))
				{
					this._nivelAccesoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivelAcceso", DbType="VarChar(13)")]
		public string nivelAcceso
		{
			get
			{
				return this._nivelAcceso;
			}
			set
			{
				if ((this._nivelAcceso != value))
				{
					this._nivelAcceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSUCURSAL", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string IDSUCURSAL
		{
			get
			{
				return this._IDSUCURSAL;
			}
			set
			{
				if ((this._IDSUCURSAL != value))
				{
					this._IDSUCURSAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUCURSAL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string SUCURSAL
		{
			get
			{
				return this._SUCURSAL;
			}
			set
			{
				if ((this._SUCURSAL != value))
				{
					this._SUCURSAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puerdaId", DbType="Int NOT NULL")]
		public int puerdaId
		{
			get
			{
				return this._puerdaId;
			}
			set
			{
				if ((this._puerdaId != value))
				{
					this._puerdaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puerta", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string puerta
		{
			get
			{
				return this._puerta;
			}
			set
			{
				if ((this._puerta != value))
				{
					this._puerta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpresaID", DbType="Char(3)")]
		public string EmpresaID
		{
			get
			{
				return this._EmpresaID;
			}
			set
			{
				if ((this._EmpresaID != value))
				{
					this._EmpresaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SituacionPlanilla", DbType="VarChar(20)")]
		public string SituacionPlanilla
		{
			get
			{
				return this._SituacionPlanilla;
			}
			set
			{
				if ((this._SituacionPlanilla != value))
				{
					this._SituacionPlanilla = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarioMaquinaria")]
	public partial class usuarioMaquinaria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuarioMaquinaria;
		
		private string _nroDocumento;
		
		private string _nombres;
		
		private string _codigoTrabajador;
		
		private string _usuario;
		
		private string _clave;
		
		private string _perfil;
		
		private char _estado;
		
		private string _email;
		
		private string _area;
		
		private string _RutaDeFirma;
		
		private System.Data.Linq.Binary _FIRMA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioMaquinariaChanging(int value);
    partial void OnidUsuarioMaquinariaChanged();
    partial void OnnroDocumentoChanging(string value);
    partial void OnnroDocumentoChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OncodigoTrabajadorChanging(string value);
    partial void OncodigoTrabajadorChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnperfilChanging(string value);
    partial void OnperfilChanged();
    partial void OnestadoChanging(char value);
    partial void OnestadoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnareaChanging(string value);
    partial void OnareaChanged();
    partial void OnRutaDeFirmaChanging(string value);
    partial void OnRutaDeFirmaChanged();
    partial void OnFIRMAChanging(System.Data.Linq.Binary value);
    partial void OnFIRMAChanged();
    #endregion
		
		public usuarioMaquinaria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioMaquinaria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUsuarioMaquinaria
		{
			get
			{
				return this._idUsuarioMaquinaria;
			}
			set
			{
				if ((this._idUsuarioMaquinaria != value))
				{
					this.OnidUsuarioMaquinariaChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioMaquinaria = value;
					this.SendPropertyChanged("idUsuarioMaquinaria");
					this.OnidUsuarioMaquinariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nroDocumento", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string nroDocumento
		{
			get
			{
				return this._nroDocumento;
			}
			set
			{
				if ((this._nroDocumento != value))
				{
					this.OnnroDocumentoChanging(value);
					this.SendPropertyChanging();
					this._nroDocumento = value;
					this.SendPropertyChanged("nroDocumento");
					this.OnnroDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(150)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoTrabajador", DbType="Char(13)")]
		public string codigoTrabajador
		{
			get
			{
				return this._codigoTrabajador;
			}
			set
			{
				if ((this._codigoTrabajador != value))
				{
					this.OncodigoTrabajadorChanging(value);
					this.SendPropertyChanging();
					this._codigoTrabajador = value;
					this.SendPropertyChanged("codigoTrabajador");
					this.OncodigoTrabajadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string perfil
		{
			get
			{
				return this._perfil;
			}
			set
			{
				if ((this._perfil != value))
				{
					this.OnperfilChanging(value);
					this.SendPropertyChanging();
					this._perfil = value;
					this.SendPropertyChanged("perfil");
					this.OnperfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(1) NOT NULL")]
		public char estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(45)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="VarChar(5)")]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaDeFirma", DbType="VarChar(250)")]
		public string RutaDeFirma
		{
			get
			{
				return this._RutaDeFirma;
			}
			set
			{
				if ((this._RutaDeFirma != value))
				{
					this.OnRutaDeFirmaChanging(value);
					this.SendPropertyChanging();
					this._RutaDeFirma = value;
					this.SendPropertyChanged("RutaDeFirma");
					this.OnRutaDeFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMA", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FIRMA
		{
			get
			{
				return this._FIRMA;
			}
			set
			{
				if ((this._FIRMA != value))
				{
					this.OnFIRMAChanging(value);
					this.SendPropertyChanging();
					this._FIRMA = value;
					this.SendPropertyChanged("FIRMA");
					this.OnFIRMAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ListadoCuentasBoltWeb")]
	public partial class SAS_ListadoCuentasBoltWeb
	{
		
		private int _CuentaUsuarioIdentificador;
		
		private string _NumeroDocumento;
		
		private string _ColaboradorNombresCompletos;
		
		private string _ColaboradorCodigo;
		
		private string _CuentaUsuario;
		
		private string _ClaveAcceso;
		
		private string _Perfil;
		
		private char _Estado;
		
		private string _EstadoCuentaBolt;
		
		private string _Correo;
		
		private string _AreaId;
		
		private string _RutaDeFirma;
		
		private System.Data.Linq.Binary _firma;
		
		private int _EstadoCuentaERPId;
		
		private string _EstadoCuentaERP;
		
		private string _SituacionEnPlanilla;
		
		public SAS_ListadoCuentasBoltWeb()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaUsuarioIdentificador", DbType="Int NOT NULL")]
		public int CuentaUsuarioIdentificador
		{
			get
			{
				return this._CuentaUsuarioIdentificador;
			}
			set
			{
				if ((this._CuentaUsuarioIdentificador != value))
				{
					this._CuentaUsuarioIdentificador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDocumento", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string NumeroDocumento
		{
			get
			{
				return this._NumeroDocumento;
			}
			set
			{
				if ((this._NumeroDocumento != value))
				{
					this._NumeroDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColaboradorNombresCompletos", DbType="VarChar(150)")]
		public string ColaboradorNombresCompletos
		{
			get
			{
				return this._ColaboradorNombresCompletos;
			}
			set
			{
				if ((this._ColaboradorNombresCompletos != value))
				{
					this._ColaboradorNombresCompletos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColaboradorCodigo", DbType="Char(13)")]
		public string ColaboradorCodigo
		{
			get
			{
				return this._ColaboradorCodigo;
			}
			set
			{
				if ((this._ColaboradorCodigo != value))
				{
					this._ColaboradorCodigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaUsuario", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string CuentaUsuario
		{
			get
			{
				return this._CuentaUsuario;
			}
			set
			{
				if ((this._CuentaUsuario != value))
				{
					this._CuentaUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveAcceso", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string ClaveAcceso
		{
			get
			{
				return this._ClaveAcceso;
			}
			set
			{
				if ((this._ClaveAcceso != value))
				{
					this._ClaveAcceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perfil", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string Perfil
		{
			get
			{
				return this._Perfil;
			}
			set
			{
				if ((this._Perfil != value))
				{
					this._Perfil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCuentaBolt", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string EstadoCuentaBolt
		{
			get
			{
				return this._EstadoCuentaBolt;
			}
			set
			{
				if ((this._EstadoCuentaBolt != value))
				{
					this._EstadoCuentaBolt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(45)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaId", DbType="VarChar(5)")]
		public string AreaId
		{
			get
			{
				return this._AreaId;
			}
			set
			{
				if ((this._AreaId != value))
				{
					this._AreaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RutaDeFirma", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string RutaDeFirma
		{
			get
			{
				return this._RutaDeFirma;
			}
			set
			{
				if ((this._RutaDeFirma != value))
				{
					this._RutaDeFirma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary firma
		{
			get
			{
				return this._firma;
			}
			set
			{
				if ((this._firma != value))
				{
					this._firma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCuentaERPId", DbType="Int NOT NULL")]
		public int EstadoCuentaERPId
		{
			get
			{
				return this._EstadoCuentaERPId;
			}
			set
			{
				if ((this._EstadoCuentaERPId != value))
				{
					this._EstadoCuentaERPId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCuentaERP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string EstadoCuentaERP
		{
			get
			{
				return this._EstadoCuentaERP;
			}
			set
			{
				if ((this._EstadoCuentaERP != value))
				{
					this._EstadoCuentaERP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SituacionEnPlanilla", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SituacionEnPlanilla
		{
			get
			{
				return this._SituacionEnPlanilla;
			}
			set
			{
				if ((this._SituacionEnPlanilla != value))
				{
					this._SituacionEnPlanilla = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ListadoAreaCuentaBolt")]
	public partial class SAS_ListadoAreaCuentaBolt
	{
		
		private string _AreaId;
		
		private string _perfil;
		
		public SAS_ListadoAreaCuentaBolt()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaId", DbType="VarChar(5)")]
		public string AreaId
		{
			get
			{
				return this._AreaId;
			}
			set
			{
				if ((this._AreaId != value))
				{
					this._AreaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil", DbType="VarChar(28)")]
		public string perfil
		{
			get
			{
				return this._perfil;
			}
			set
			{
				if ((this._perfil != value))
				{
					this._perfil = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ListadoPerfilCuentaBolt")]
	public partial class SAS_ListadoPerfilCuentaBolt
	{
		
		private string _PerfilId;
		
		private string _perfil;
		
		public SAS_ListadoPerfilCuentaBolt()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerfilId", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string PerfilId
		{
			get
			{
				return this._PerfilId;
			}
			set
			{
				if ((this._PerfilId != value))
				{
					this._PerfilId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil", DbType="VarChar(13)")]
		public string perfil
		{
			get
			{
				return this._perfil;
			}
			set
			{
				if ((this._perfil != value))
				{
					this._perfil = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ListadoUsuariosNISIRAvsUsuarioBoltActivos")]
	public partial class SAS_ListadoUsuariosNISIRAvsUsuarioBoltActivos
	{
		
		private string _UsuarioCodigo;
		
		private string _PersonalCodigo;
		
		private string _PersonalDocumento;
		
		private System.Nullable<int> _EstadoCuentaERP;
		
		private string _PersonalNombre;
		
		private string _Correo;
		
		private string _Clave;
		
		private string _UsuarioCodigoBoltWeb;
		
		private string _situacionPlanilla;
		
		public SAS_ListadoUsuariosNISIRAvsUsuarioBoltActivos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCodigo", DbType="VarChar(20)")]
		public string UsuarioCodigo
		{
			get
			{
				return this._UsuarioCodigo;
			}
			set
			{
				if ((this._UsuarioCodigo != value))
				{
					this._UsuarioCodigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalCodigo", DbType="VarChar(8)")]
		public string PersonalCodigo
		{
			get
			{
				return this._PersonalCodigo;
			}
			set
			{
				if ((this._PersonalCodigo != value))
				{
					this._PersonalCodigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalDocumento", DbType="VarChar(20)")]
		public string PersonalDocumento
		{
			get
			{
				return this._PersonalDocumento;
			}
			set
			{
				if ((this._PersonalDocumento != value))
				{
					this._PersonalDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCuentaERP", DbType="Int")]
		public System.Nullable<int> EstadoCuentaERP
		{
			get
			{
				return this._EstadoCuentaERP;
			}
			set
			{
				if ((this._EstadoCuentaERP != value))
				{
					this._EstadoCuentaERP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalNombre", DbType="VarChar(80)")]
		public string PersonalNombre
		{
			get
			{
				return this._PersonalNombre;
			}
			set
			{
				if ((this._PersonalNombre != value))
				{
					this._PersonalNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="VarChar(8)")]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this._Clave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioCodigoBoltWeb", DbType="VarChar(12)")]
		public string UsuarioCodigoBoltWeb
		{
			get
			{
				return this._UsuarioCodigoBoltWeb;
			}
			set
			{
				if ((this._UsuarioCodigoBoltWeb != value))
				{
					this._UsuarioCodigoBoltWeb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacionPlanilla", DbType="VarChar(20)")]
		public string situacionPlanilla
		{
			get
			{
				return this._situacionPlanilla;
			}
			set
			{
				if ((this._situacionPlanilla != value))
				{
					this._situacionPlanilla = value;
				}
			}
		}
	}
	
	public partial class SAS_ConsumidorFechaAplicacionCListadoPorAnioResult
	{
		
		private string _IdEmpresa;
		
		private string _ConsumidorId;
		
		private string _SiembraId;
		
		private string _CampanaAgricolaId;
		
		private decimal _AnioCampaña;
		
		private System.Nullable<System.DateTime> _FechaAplicacionEnFormacion;
		
		private System.Nullable<System.DateTime> _FechaAplicacionEnProduccion;
		
		private char _TipoRegistro;
		
		private System.Nullable<byte> _Estado;
		
		private string _Observacion;
		
		private System.Nullable<decimal> _area;
		
		private System.Nullable<System.DateTime> _inicioCampana;
		
		private System.Nullable<System.DateTime> _finalCampana;
		
		private string _cultivo;
		
		private string _variedad;
		
		private string _tipoCultivo;
		
		private string _sector;
		
		private string _CODIGO_CONTROL;
		
		private string _CODIGO_FITOSOFT;
		
		public SAS_ConsumidorFechaAplicacionCListadoPorAnioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsumidorId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ConsumidorId
		{
			get
			{
				return this._ConsumidorId;
			}
			set
			{
				if ((this._ConsumidorId != value))
				{
					this._ConsumidorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiembraId", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string SiembraId
		{
			get
			{
				return this._SiembraId;
			}
			set
			{
				if ((this._SiembraId != value))
				{
					this._SiembraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampanaAgricolaId", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CampanaAgricolaId
		{
			get
			{
				return this._CampanaAgricolaId;
			}
			set
			{
				if ((this._CampanaAgricolaId != value))
				{
					this._CampanaAgricolaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnioCampaña", DbType="Decimal(4,0) NOT NULL")]
		public decimal AnioCampaña
		{
			get
			{
				return this._AnioCampaña;
			}
			set
			{
				if ((this._AnioCampaña != value))
				{
					this._AnioCampaña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionEnFormacion", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaAplicacionEnFormacion
		{
			get
			{
				return this._FechaAplicacionEnFormacion;
			}
			set
			{
				if ((this._FechaAplicacionEnFormacion != value))
				{
					this._FechaAplicacionEnFormacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacionEnProduccion", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaAplicacionEnProduccion
		{
			get
			{
				return this._FechaAplicacionEnProduccion;
			}
			set
			{
				if ((this._FechaAplicacionEnProduccion != value))
				{
					this._FechaAplicacionEnProduccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRegistro", DbType="Char(1) NOT NULL")]
		public char TipoRegistro
		{
			get
			{
				return this._TipoRegistro;
			}
			set
			{
				if ((this._TipoRegistro != value))
				{
					this._TipoRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt")]
		public System.Nullable<byte> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(200)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="Decimal(15,4)")]
		public System.Nullable<decimal> area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this._area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inicioCampana", DbType="DateTime")]
		public System.Nullable<System.DateTime> inicioCampana
		{
			get
			{
				return this._inicioCampana;
			}
			set
			{
				if ((this._inicioCampana != value))
				{
					this._inicioCampana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finalCampana", DbType="DateTime")]
		public System.Nullable<System.DateTime> finalCampana
		{
			get
			{
				return this._finalCampana;
			}
			set
			{
				if ((this._finalCampana != value))
				{
					this._finalCampana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cultivo", DbType="VarChar(50)")]
		public string cultivo
		{
			get
			{
				return this._cultivo;
			}
			set
			{
				if ((this._cultivo != value))
				{
					this._cultivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_variedad", DbType="VarChar(80)")]
		public string variedad
		{
			get
			{
				return this._variedad;
			}
			set
			{
				if ((this._variedad != value))
				{
					this._variedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoCultivo", DbType="VarChar(14)")]
		public string tipoCultivo
		{
			get
			{
				return this._tipoCultivo;
			}
			set
			{
				if ((this._tipoCultivo != value))
				{
					this._tipoCultivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sector", DbType="VarChar(200)")]
		public string sector
		{
			get
			{
				return this._sector;
			}
			set
			{
				if ((this._sector != value))
				{
					this._sector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_CONTROL", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string CODIGO_CONTROL
		{
			get
			{
				return this._CODIGO_CONTROL;
			}
			set
			{
				if ((this._CODIGO_CONTROL != value))
				{
					this._CODIGO_CONTROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_FITOSOFT", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string CODIGO_FITOSOFT
		{
			get
			{
				return this._CODIGO_FITOSOFT;
			}
			set
			{
				if ((this._CODIGO_FITOSOFT != value))
				{
					this._CODIGO_FITOSOFT = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
