#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SSOMA")]
	public partial class BoltSSTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCapacitacionArea(CapacitacionArea instance);
    partial void UpdateCapacitacionArea(CapacitacionArea instance);
    partial void DeleteCapacitacionArea(CapacitacionArea instance);
    partial void InsertTemaArea(TemaArea instance);
    partial void UpdateTemaArea(TemaArea instance);
    partial void DeleteTemaArea(TemaArea instance);
    partial void InsertCapacitacionCapacitador(CapacitacionCapacitador instance);
    partial void UpdateCapacitacionCapacitador(CapacitacionCapacitador instance);
    partial void DeleteCapacitacionCapacitador(CapacitacionCapacitador instance);
    partial void InsertCapacitacionDetalle(CapacitacionDetalle instance);
    partial void UpdateCapacitacionDetalle(CapacitacionDetalle instance);
    partial void DeleteCapacitacionDetalle(CapacitacionDetalle instance);
    partial void InsertCapacitacionFotografia(CapacitacionFotografia instance);
    partial void UpdateCapacitacionFotografia(CapacitacionFotografia instance);
    partial void DeleteCapacitacionFotografia(CapacitacionFotografia instance);
    partial void InsertCapacitacionTema(CapacitacionTema instance);
    partial void UpdateCapacitacionTema(CapacitacionTema instance);
    partial void DeleteCapacitacionTema(CapacitacionTema instance);
    partial void InsertCapacitacionTipo(CapacitacionTipo instance);
    partial void UpdateCapacitacionTipo(CapacitacionTipo instance);
    partial void DeleteCapacitacionTipo(CapacitacionTipo instance);
    partial void InsertPersonalNuevo(PersonalNuevo instance);
    partial void UpdatePersonalNuevo(PersonalNuevo instance);
    partial void DeletePersonalNuevo(PersonalNuevo instance);
    partial void InsertTema(Tema instance);
    partial void UpdateTema(Tema instance);
    partial void DeleteTema(Tema instance);
    partial void InsertCapacitacionCabecera(CapacitacionCabecera instance);
    partial void UpdateCapacitacionCabecera(CapacitacionCabecera instance);
    partial void DeleteCapacitacionCabecera(CapacitacionCabecera instance);
    #endregion
		
		public BoltSSTDataContext() : 
				base(global::Asistencia.Datos.Properties.Settings.Default.SSOMAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BoltSSTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoltSSTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoltSSTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoltSSTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ListadoAsistenciaPorCapacitacion> ListadoAsistenciaPorCapacitacions
		{
			get
			{
				return this.GetTable<ListadoAsistenciaPorCapacitacion>();
			}
		}
		
		public System.Data.Linq.Table<CapacitacionArea> CapacitacionAreas
		{
			get
			{
				return this.GetTable<CapacitacionArea>();
			}
		}
		
		public System.Data.Linq.Table<TemaArea> TemaAreas
		{
			get
			{
				return this.GetTable<TemaArea>();
			}
		}
		
		public System.Data.Linq.Table<CapacitacionCapacitador> CapacitacionCapacitadors
		{
			get
			{
				return this.GetTable<CapacitacionCapacitador>();
			}
		}
		
		public System.Data.Linq.Table<CapacitacionDetalle> CapacitacionDetalles
		{
			get
			{
				return this.GetTable<CapacitacionDetalle>();
			}
		}
		
		public System.Data.Linq.Table<CapacitacionFotografia> CapacitacionFotografias
		{
			get
			{
				return this.GetTable<CapacitacionFotografia>();
			}
		}
		
		public System.Data.Linq.Table<CapacitacionTema> CapacitacionTemas
		{
			get
			{
				return this.GetTable<CapacitacionTema>();
			}
		}
		
		public System.Data.Linq.Table<CapacitacionTipo> CapacitacionTipos
		{
			get
			{
				return this.GetTable<CapacitacionTipo>();
			}
		}
		
		public System.Data.Linq.Table<PersonalNuevo> PersonalNuevos
		{
			get
			{
				return this.GetTable<PersonalNuevo>();
			}
		}
		
		public System.Data.Linq.Table<Tema> Temas
		{
			get
			{
				return this.GetTable<Tema>();
			}
		}
		
		public System.Data.Linq.Table<CapacitacionCabecera> CapacitacionCabeceras
		{
			get
			{
				return this.GetTable<CapacitacionCabecera>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoTemasParaCapacitacionByTemaId")]
		public ISingleResult<SAS_ListadoTemasParaCapacitacionByTemaIdResult> SAS_ListadoTemasParaCapacitacionByTemaId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemaId", DbType="VarChar(3)")] string temaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), temaId);
			return ((ISingleResult<SAS_ListadoTemasParaCapacitacionByTemaIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListadoRegistroCapacitacionesPorPeriodo")]
		public ISingleResult<ListadoRegistroCapacitacionesPorPeriodoResult> ListadoRegistroCapacitacionesPorPeriodo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string hasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta);
			return ((ISingleResult<ListadoRegistroCapacitacionesPorPeriodoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListadoRegistroCapacitacionesPorID")]
		public ISingleResult<ListadoRegistroCapacitacionesPorIDResult> ListadoRegistroCapacitacionesPorID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CapacitacionID", DbType="VarChar(17)")] string capacitacionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), capacitacionID);
			return ((ISingleResult<ListadoRegistroCapacitacionesPorIDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListadoAsistenciaPorCapacitacion")]
	public partial class ListadoAsistenciaPorCapacitacion
	{
		
		private string _CapacitacionID;
		
		private System.Nullable<int> _Asistentes;
		
		public ListadoAsistenciaPorCapacitacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					this._CapacitacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asistentes", DbType="Int")]
		public System.Nullable<int> Asistentes
		{
			get
			{
				return this._Asistentes;
			}
			set
			{
				if ((this._Asistentes != value))
				{
					this._Asistentes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapacitacionArea")]
	public partial class CapacitacionArea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CapacitacionAreaID;
		
		private string _CapacitacionID;
		
		private string _AreaId;
		
		private EntityRef<CapacitacionCabecera> _CapacitacionCabecera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacitacionAreaIDChanging(string value);
    partial void OnCapacitacionAreaIDChanged();
    partial void OnCapacitacionIDChanging(string value);
    partial void OnCapacitacionIDChanged();
    partial void OnAreaIdChanging(string value);
    partial void OnAreaIdChanged();
    #endregion
		
		public CapacitacionArea()
		{
			this._CapacitacionCabecera = default(EntityRef<CapacitacionCabecera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionAreaID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CapacitacionAreaID
		{
			get
			{
				return this._CapacitacionAreaID;
			}
			set
			{
				if ((this._CapacitacionAreaID != value))
				{
					this.OnCapacitacionAreaIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionAreaID = value;
					this.SendPropertyChanged("CapacitacionAreaID");
					this.OnCapacitacionAreaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					if (this._CapacitacionCabecera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCapacitacionIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionID = value;
					this.SendPropertyChanged("CapacitacionID");
					this.OnCapacitacionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaId", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string AreaId
		{
			get
			{
				return this._AreaId;
			}
			set
			{
				if ((this._AreaId != value))
				{
					this.OnAreaIdChanging(value);
					this.SendPropertyChanging();
					this._AreaId = value;
					this.SendPropertyChanged("AreaId");
					this.OnAreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionArea", Storage="_CapacitacionCabecera", ThisKey="CapacitacionID", OtherKey="CapacitacionID", IsForeignKey=true)]
		public CapacitacionCabecera CapacitacionCabecera
		{
			get
			{
				return this._CapacitacionCabecera.Entity;
			}
			set
			{
				CapacitacionCabecera previousValue = this._CapacitacionCabecera.Entity;
				if (((previousValue != value) 
							|| (this._CapacitacionCabecera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CapacitacionCabecera.Entity = null;
						previousValue.CapacitacionAreas.Remove(this);
					}
					this._CapacitacionCabecera.Entity = value;
					if ((value != null))
					{
						value.CapacitacionAreas.Add(this);
						this._CapacitacionID = value.CapacitacionID;
					}
					else
					{
						this._CapacitacionID = default(string);
					}
					this.SendPropertyChanged("CapacitacionCabecera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TemaArea")]
	public partial class TemaArea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TemaAreaId;
		
		private string _TemaID;
		
		private string _AreaID;
		
		private byte _Estado;
		
		private EntityRef<Tema> _Tema;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTemaAreaIdChanging(int value);
    partial void OnTemaAreaIdChanged();
    partial void OnTemaIDChanging(string value);
    partial void OnTemaIDChanged();
    partial void OnAreaIDChanging(string value);
    partial void OnAreaIDChanged();
    partial void OnEstadoChanging(byte value);
    partial void OnEstadoChanged();
    #endregion
		
		public TemaArea()
		{
			this._Tema = default(EntityRef<Tema>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaAreaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TemaAreaId
		{
			get
			{
				return this._TemaAreaId;
			}
			set
			{
				if ((this._TemaAreaId != value))
				{
					this.OnTemaAreaIdChanging(value);
					this.SendPropertyChanging();
					this._TemaAreaId = value;
					this.SendPropertyChanged("TemaAreaId");
					this.OnTemaAreaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string TemaID
		{
			get
			{
				return this._TemaID;
			}
			set
			{
				if ((this._TemaID != value))
				{
					if (this._Tema.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTemaIDChanging(value);
					this.SendPropertyChanging();
					this._TemaID = value;
					this.SendPropertyChanged("TemaID");
					this.OnTemaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaID", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string AreaID
		{
			get
			{
				return this._AreaID;
			}
			set
			{
				if ((this._AreaID != value))
				{
					this.OnAreaIDChanging(value);
					this.SendPropertyChanging();
					this._AreaID = value;
					this.SendPropertyChanged("AreaID");
					this.OnAreaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tema_TemaArea", Storage="_Tema", ThisKey="TemaID", OtherKey="TemaID", IsForeignKey=true)]
		public Tema Tema
		{
			get
			{
				return this._Tema.Entity;
			}
			set
			{
				Tema previousValue = this._Tema.Entity;
				if (((previousValue != value) 
							|| (this._Tema.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tema.Entity = null;
						previousValue.TemaAreas.Remove(this);
					}
					this._Tema.Entity = value;
					if ((value != null))
					{
						value.TemaAreas.Add(this);
						this._TemaID = value.TemaID;
					}
					else
					{
						this._TemaID = default(string);
					}
					this.SendPropertyChanged("Tema");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapacitacionCapacitador")]
	public partial class CapacitacionCapacitador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CapacitacionCapacitadorID;
		
		private string _ResponsableID;
		
		private string _CapacitacionID;
		
		private string _Firma;
		
		private EntityRef<CapacitacionCabecera> _CapacitacionCabecera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacitacionCapacitadorIDChanging(string value);
    partial void OnCapacitacionCapacitadorIDChanged();
    partial void OnResponsableIDChanging(string value);
    partial void OnResponsableIDChanged();
    partial void OnCapacitacionIDChanging(string value);
    partial void OnCapacitacionIDChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    #endregion
		
		public CapacitacionCapacitador()
		{
			this._CapacitacionCabecera = default(EntityRef<CapacitacionCabecera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionCapacitadorID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CapacitacionCapacitadorID
		{
			get
			{
				return this._CapacitacionCapacitadorID;
			}
			set
			{
				if ((this._CapacitacionCapacitadorID != value))
				{
					this.OnCapacitacionCapacitadorIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionCapacitadorID = value;
					this.SendPropertyChanged("CapacitacionCapacitadorID");
					this.OnCapacitacionCapacitadorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponsableID", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string ResponsableID
		{
			get
			{
				return this._ResponsableID;
			}
			set
			{
				if ((this._ResponsableID != value))
				{
					this.OnResponsableIDChanging(value);
					this.SendPropertyChanging();
					this._ResponsableID = value;
					this.SendPropertyChanged("ResponsableID");
					this.OnResponsableIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					if (this._CapacitacionCabecera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCapacitacionIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionID = value;
					this.SendPropertyChanged("CapacitacionID");
					this.OnCapacitacionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionCapacitador", Storage="_CapacitacionCabecera", ThisKey="CapacitacionID", OtherKey="CapacitacionID", IsForeignKey=true)]
		public CapacitacionCabecera CapacitacionCabecera
		{
			get
			{
				return this._CapacitacionCabecera.Entity;
			}
			set
			{
				CapacitacionCabecera previousValue = this._CapacitacionCabecera.Entity;
				if (((previousValue != value) 
							|| (this._CapacitacionCabecera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CapacitacionCabecera.Entity = null;
						previousValue.CapacitacionCapacitadors.Remove(this);
					}
					this._CapacitacionCabecera.Entity = value;
					if ((value != null))
					{
						value.CapacitacionCapacitadors.Add(this);
						this._CapacitacionID = value.CapacitacionID;
					}
					else
					{
						this._CapacitacionID = default(string);
					}
					this.SendPropertyChanged("CapacitacionCabecera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapacitacionDetalle")]
	public partial class CapacitacionDetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CapacitacionDetalleID;
		
		private string _CapacitacionID;
		
		private string _PersonalID;
		
		private string _NumeroDocumento;
		
		private string _Nombres;
		
		private string _Cargo;
		
		private string _Area;
		
		private string _NumeroCelular;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private string _Firma;
		
		private string _DNI;
		
		private System.Nullable<byte> _Estado;
		
		private EntityRef<CapacitacionCabecera> _CapacitacionCabecera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacitacionDetalleIDChanging(string value);
    partial void OnCapacitacionDetalleIDChanged();
    partial void OnCapacitacionIDChanging(string value);
    partial void OnCapacitacionIDChanged();
    partial void OnPersonalIDChanging(string value);
    partial void OnPersonalIDChanged();
    partial void OnNumeroDocumentoChanging(string value);
    partial void OnNumeroDocumentoChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnNumeroCelularChanging(string value);
    partial void OnNumeroCelularChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnEstadoChanging(System.Nullable<byte> value);
    partial void OnEstadoChanged();
    #endregion
		
		public CapacitacionDetalle()
		{
			this._CapacitacionCabecera = default(EntityRef<CapacitacionCabecera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionDetalleID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CapacitacionDetalleID
		{
			get
			{
				return this._CapacitacionDetalleID;
			}
			set
			{
				if ((this._CapacitacionDetalleID != value))
				{
					this.OnCapacitacionDetalleIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionDetalleID = value;
					this.SendPropertyChanged("CapacitacionDetalleID");
					this.OnCapacitacionDetalleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					if (this._CapacitacionCabecera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCapacitacionIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionID = value;
					this.SendPropertyChanged("CapacitacionID");
					this.OnCapacitacionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalID", DbType="VarChar(12)")]
		public string PersonalID
		{
			get
			{
				return this._PersonalID;
			}
			set
			{
				if ((this._PersonalID != value))
				{
					this.OnPersonalIDChanging(value);
					this.SendPropertyChanging();
					this._PersonalID = value;
					this.SendPropertyChanged("PersonalID");
					this.OnPersonalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDocumento", DbType="VarChar(12)")]
		public string NumeroDocumento
		{
			get
			{
				return this._NumeroDocumento;
			}
			set
			{
				if ((this._NumeroDocumento != value))
				{
					this.OnNumeroDocumentoChanging(value);
					this.SendPropertyChanging();
					this._NumeroDocumento = value;
					this.SendPropertyChanged("NumeroDocumento");
					this.OnNumeroDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="NChar(250)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="NChar(250)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="NChar(250)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCelular", DbType="VarChar(12)")]
		public string NumeroCelular
		{
			get
			{
				return this._NumeroCelular;
			}
			set
			{
				if ((this._NumeroCelular != value))
				{
					this.OnNumeroCelularChanging(value);
					this.SendPropertyChanging();
					this._NumeroCelular = value;
					this.SendPropertyChanged("NumeroCelular");
					this.OnNumeroCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(MAX)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(12)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt")]
		public System.Nullable<byte> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionDetalle", Storage="_CapacitacionCabecera", ThisKey="CapacitacionID", OtherKey="CapacitacionID", IsForeignKey=true)]
		public CapacitacionCabecera CapacitacionCabecera
		{
			get
			{
				return this._CapacitacionCabecera.Entity;
			}
			set
			{
				CapacitacionCabecera previousValue = this._CapacitacionCabecera.Entity;
				if (((previousValue != value) 
							|| (this._CapacitacionCabecera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CapacitacionCabecera.Entity = null;
						previousValue.CapacitacionDetalles.Remove(this);
					}
					this._CapacitacionCabecera.Entity = value;
					if ((value != null))
					{
						value.CapacitacionDetalles.Add(this);
						this._CapacitacionID = value.CapacitacionID;
					}
					else
					{
						this._CapacitacionID = default(string);
					}
					this.SendPropertyChanged("CapacitacionCabecera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapacitacionFotografia")]
	public partial class CapacitacionFotografia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CapacitacionFotografiaID;
		
		private string _CapacitacionID;
		
		private string _Fotografia;
		
		private string _Fotografia2;
		
		private string _Fotografia3;
		
		private System.Nullable<byte> _Estado;
		
		private EntityRef<CapacitacionCabecera> _CapacitacionCabecera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacitacionFotografiaIDChanging(string value);
    partial void OnCapacitacionFotografiaIDChanged();
    partial void OnCapacitacionIDChanging(string value);
    partial void OnCapacitacionIDChanged();
    partial void OnFotografiaChanging(string value);
    partial void OnFotografiaChanged();
    partial void OnFotografia2Changing(string value);
    partial void OnFotografia2Changed();
    partial void OnFotografia3Changing(string value);
    partial void OnFotografia3Changed();
    partial void OnEstadoChanging(System.Nullable<byte> value);
    partial void OnEstadoChanged();
    #endregion
		
		public CapacitacionFotografia()
		{
			this._CapacitacionCabecera = default(EntityRef<CapacitacionCabecera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionFotografiaID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CapacitacionFotografiaID
		{
			get
			{
				return this._CapacitacionFotografiaID;
			}
			set
			{
				if ((this._CapacitacionFotografiaID != value))
				{
					this.OnCapacitacionFotografiaIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionFotografiaID = value;
					this.SendPropertyChanged("CapacitacionFotografiaID");
					this.OnCapacitacionFotografiaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					if (this._CapacitacionCabecera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCapacitacionIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionID = value;
					this.SendPropertyChanged("CapacitacionID");
					this.OnCapacitacionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fotografia", DbType="VarChar(MAX)")]
		public string Fotografia
		{
			get
			{
				return this._Fotografia;
			}
			set
			{
				if ((this._Fotografia != value))
				{
					this.OnFotografiaChanging(value);
					this.SendPropertyChanging();
					this._Fotografia = value;
					this.SendPropertyChanged("Fotografia");
					this.OnFotografiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fotografia2", DbType="VarChar(MAX)")]
		public string Fotografia2
		{
			get
			{
				return this._Fotografia2;
			}
			set
			{
				if ((this._Fotografia2 != value))
				{
					this.OnFotografia2Changing(value);
					this.SendPropertyChanging();
					this._Fotografia2 = value;
					this.SendPropertyChanged("Fotografia2");
					this.OnFotografia2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fotografia3", DbType="VarChar(MAX)")]
		public string Fotografia3
		{
			get
			{
				return this._Fotografia3;
			}
			set
			{
				if ((this._Fotografia3 != value))
				{
					this.OnFotografia3Changing(value);
					this.SendPropertyChanging();
					this._Fotografia3 = value;
					this.SendPropertyChanged("Fotografia3");
					this.OnFotografia3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt")]
		public System.Nullable<byte> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionFotografia", Storage="_CapacitacionCabecera", ThisKey="CapacitacionID", OtherKey="CapacitacionID", IsForeignKey=true)]
		public CapacitacionCabecera CapacitacionCabecera
		{
			get
			{
				return this._CapacitacionCabecera.Entity;
			}
			set
			{
				CapacitacionCabecera previousValue = this._CapacitacionCabecera.Entity;
				if (((previousValue != value) 
							|| (this._CapacitacionCabecera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CapacitacionCabecera.Entity = null;
						previousValue.CapacitacionFotografias.Remove(this);
					}
					this._CapacitacionCabecera.Entity = value;
					if ((value != null))
					{
						value.CapacitacionFotografias.Add(this);
						this._CapacitacionID = value.CapacitacionID;
					}
					else
					{
						this._CapacitacionID = default(string);
					}
					this.SendPropertyChanged("CapacitacionCabecera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapacitacionTema")]
	public partial class CapacitacionTema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CapacitacionTemaID;
		
		private string _CapacitacionID;
		
		private string _TemaID;
		
		private System.Nullable<byte> _Estado;
		
		private EntityRef<Tema> _Tema;
		
		private EntityRef<CapacitacionCabecera> _CapacitacionCabecera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacitacionTemaIDChanging(string value);
    partial void OnCapacitacionTemaIDChanged();
    partial void OnCapacitacionIDChanging(string value);
    partial void OnCapacitacionIDChanged();
    partial void OnTemaIDChanging(string value);
    partial void OnTemaIDChanged();
    partial void OnEstadoChanging(System.Nullable<byte> value);
    partial void OnEstadoChanged();
    #endregion
		
		public CapacitacionTema()
		{
			this._Tema = default(EntityRef<Tema>);
			this._CapacitacionCabecera = default(EntityRef<CapacitacionCabecera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionTemaID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CapacitacionTemaID
		{
			get
			{
				return this._CapacitacionTemaID;
			}
			set
			{
				if ((this._CapacitacionTemaID != value))
				{
					this.OnCapacitacionTemaIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionTemaID = value;
					this.SendPropertyChanged("CapacitacionTemaID");
					this.OnCapacitacionTemaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					if (this._CapacitacionCabecera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCapacitacionIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionID = value;
					this.SendPropertyChanged("CapacitacionID");
					this.OnCapacitacionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string TemaID
		{
			get
			{
				return this._TemaID;
			}
			set
			{
				if ((this._TemaID != value))
				{
					if (this._Tema.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTemaIDChanging(value);
					this.SendPropertyChanging();
					this._TemaID = value;
					this.SendPropertyChanged("TemaID");
					this.OnTemaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt")]
		public System.Nullable<byte> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tema_CapacitacionTema", Storage="_Tema", ThisKey="TemaID", OtherKey="TemaID", IsForeignKey=true)]
		public Tema Tema
		{
			get
			{
				return this._Tema.Entity;
			}
			set
			{
				Tema previousValue = this._Tema.Entity;
				if (((previousValue != value) 
							|| (this._Tema.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tema.Entity = null;
						previousValue.CapacitacionTemas.Remove(this);
					}
					this._Tema.Entity = value;
					if ((value != null))
					{
						value.CapacitacionTemas.Add(this);
						this._TemaID = value.TemaID;
					}
					else
					{
						this._TemaID = default(string);
					}
					this.SendPropertyChanged("Tema");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionTema", Storage="_CapacitacionCabecera", ThisKey="CapacitacionID", OtherKey="CapacitacionID", IsForeignKey=true)]
		public CapacitacionCabecera CapacitacionCabecera
		{
			get
			{
				return this._CapacitacionCabecera.Entity;
			}
			set
			{
				CapacitacionCabecera previousValue = this._CapacitacionCabecera.Entity;
				if (((previousValue != value) 
							|| (this._CapacitacionCabecera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CapacitacionCabecera.Entity = null;
						previousValue.CapacitacionTemas.Remove(this);
					}
					this._CapacitacionCabecera.Entity = value;
					if ((value != null))
					{
						value.CapacitacionTemas.Add(this);
						this._CapacitacionID = value.CapacitacionID;
					}
					else
					{
						this._CapacitacionID = default(string);
					}
					this.SendPropertyChanged("CapacitacionCabecera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapacitacionTipo")]
	public partial class CapacitacionTipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CapacitacionTipoID;
		
		private string _Descripcion;
		
		private bool _Estado;
		
		private EntitySet<CapacitacionCabecera> _CapacitacionCabeceras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacitacionTipoIDChanging(string value);
    partial void OnCapacitacionTipoIDChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    #endregion
		
		public CapacitacionTipo()
		{
			this._CapacitacionCabeceras = new EntitySet<CapacitacionCabecera>(new Action<CapacitacionCabecera>(this.attach_CapacitacionCabeceras), new Action<CapacitacionCabecera>(this.detach_CapacitacionCabeceras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionTipoID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CapacitacionTipoID
		{
			get
			{
				return this._CapacitacionTipoID;
			}
			set
			{
				if ((this._CapacitacionTipoID != value))
				{
					this.OnCapacitacionTipoIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionTipoID = value;
					this.SendPropertyChanged("CapacitacionTipoID");
					this.OnCapacitacionTipoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionTipo_CapacitacionCabecera", Storage="_CapacitacionCabeceras", ThisKey="CapacitacionTipoID", OtherKey="CapacitacionTipoID")]
		public EntitySet<CapacitacionCabecera> CapacitacionCabeceras
		{
			get
			{
				return this._CapacitacionCabeceras;
			}
			set
			{
				this._CapacitacionCabeceras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CapacitacionCabeceras(CapacitacionCabecera entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionTipo = this;
		}
		
		private void detach_CapacitacionCabeceras(CapacitacionCabecera entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionTipo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonalNuevo")]
	public partial class PersonalNuevo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PersonalNuevoID;
		
		private string _DNI;
		
		private string _Nombres;
		
		private string _Area;
		
		private string _Gerencia;
		
		private string _Cargo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonalNuevoIDChanging(string value);
    partial void OnPersonalNuevoIDChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnGerenciaChanging(string value);
    partial void OnGerenciaChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    #endregion
		
		public PersonalNuevo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalNuevoID", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string PersonalNuevoID
		{
			get
			{
				return this._PersonalNuevoID;
			}
			set
			{
				if ((this._PersonalNuevoID != value))
				{
					this.OnPersonalNuevoIDChanging(value);
					this.SendPropertyChanging();
					this._PersonalNuevoID = value;
					this.SendPropertyChanged("PersonalNuevoID");
					this.OnPersonalNuevoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(150)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(150)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gerencia", DbType="VarChar(150)")]
		public string Gerencia
		{
			get
			{
				return this._Gerencia;
			}
			set
			{
				if ((this._Gerencia != value))
				{
					this.OnGerenciaChanging(value);
					this.SendPropertyChanging();
					this._Gerencia = value;
					this.SendPropertyChanged("Gerencia");
					this.OnGerenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(150)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tema")]
	public partial class Tema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TemaID;
		
		private string _Descripcion;
		
		private decimal _FrecuenciaCapacitacion;
		
		private bool _Estado;
		
		private EntitySet<TemaArea> _TemaAreas;
		
		private EntitySet<CapacitacionTema> _CapacitacionTemas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTemaIDChanging(string value);
    partial void OnTemaIDChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFrecuenciaCapacitacionChanging(decimal value);
    partial void OnFrecuenciaCapacitacionChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    #endregion
		
		public Tema()
		{
			this._TemaAreas = new EntitySet<TemaArea>(new Action<TemaArea>(this.attach_TemaAreas), new Action<TemaArea>(this.detach_TemaAreas));
			this._CapacitacionTemas = new EntitySet<CapacitacionTema>(new Action<CapacitacionTema>(this.attach_CapacitacionTemas), new Action<CapacitacionTema>(this.detach_CapacitacionTemas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TemaID
		{
			get
			{
				return this._TemaID;
			}
			set
			{
				if ((this._TemaID != value))
				{
					this.OnTemaIDChanging(value);
					this.SendPropertyChanging();
					this._TemaID = value;
					this.SendPropertyChanged("TemaID");
					this.OnTemaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrecuenciaCapacitacion", DbType="Decimal(6,2) NOT NULL")]
		public decimal FrecuenciaCapacitacion
		{
			get
			{
				return this._FrecuenciaCapacitacion;
			}
			set
			{
				if ((this._FrecuenciaCapacitacion != value))
				{
					this.OnFrecuenciaCapacitacionChanging(value);
					this.SendPropertyChanging();
					this._FrecuenciaCapacitacion = value;
					this.SendPropertyChanged("FrecuenciaCapacitacion");
					this.OnFrecuenciaCapacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tema_TemaArea", Storage="_TemaAreas", ThisKey="TemaID", OtherKey="TemaID")]
		public EntitySet<TemaArea> TemaAreas
		{
			get
			{
				return this._TemaAreas;
			}
			set
			{
				this._TemaAreas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tema_CapacitacionTema", Storage="_CapacitacionTemas", ThisKey="TemaID", OtherKey="TemaID")]
		public EntitySet<CapacitacionTema> CapacitacionTemas
		{
			get
			{
				return this._CapacitacionTemas;
			}
			set
			{
				this._CapacitacionTemas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TemaAreas(TemaArea entity)
		{
			this.SendPropertyChanging();
			entity.Tema = this;
		}
		
		private void detach_TemaAreas(TemaArea entity)
		{
			this.SendPropertyChanging();
			entity.Tema = null;
		}
		
		private void attach_CapacitacionTemas(CapacitacionTema entity)
		{
			this.SendPropertyChanging();
			entity.Tema = this;
		}
		
		private void detach_CapacitacionTemas(CapacitacionTema entity)
		{
			this.SendPropertyChanging();
			entity.Tema = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CapacitacionCabecera")]
	public partial class CapacitacionCabecera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CapacitacionID;
		
		private string _CapacitacionTipoID;
		
		private System.DateTime _FechaCapacitacion;
		
		private string _Ubicación;
		
		private string _LatLong;
		
		private System.Nullable<System.DateTime> _HoraInicio;
		
		private System.Nullable<System.DateTime> _HoraFin;
		
		private string _Observacion;
		
		private System.DateTime _FechaRegistro;
		
		private string _PDFRuta;
		
		private System.Nullable<int> _PDFPrint;
		
		private string _EstadoID;
		
		private int _Correlativo;
		
		private string _IdReferencia;
		
		private EntitySet<CapacitacionArea> _CapacitacionAreas;
		
		private EntitySet<CapacitacionCapacitador> _CapacitacionCapacitadors;
		
		private EntitySet<CapacitacionDetalle> _CapacitacionDetalles;
		
		private EntitySet<CapacitacionFotografia> _CapacitacionFotografias;
		
		private EntitySet<CapacitacionTema> _CapacitacionTemas;
		
		private EntityRef<CapacitacionTipo> _CapacitacionTipo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCapacitacionIDChanging(string value);
    partial void OnCapacitacionIDChanged();
    partial void OnCapacitacionTipoIDChanging(string value);
    partial void OnCapacitacionTipoIDChanged();
    partial void OnFechaCapacitacionChanging(System.DateTime value);
    partial void OnFechaCapacitacionChanged();
    partial void OnUbicaciónChanging(string value);
    partial void OnUbicaciónChanged();
    partial void OnLatLongChanging(string value);
    partial void OnLatLongChanged();
    partial void OnHoraInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnHoraInicioChanged();
    partial void OnHoraFinChanging(System.Nullable<System.DateTime> value);
    partial void OnHoraFinChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnPDFRutaChanging(string value);
    partial void OnPDFRutaChanged();
    partial void OnPDFPrintChanging(System.Nullable<int> value);
    partial void OnPDFPrintChanged();
    partial void OnEstadoIDChanging(string value);
    partial void OnEstadoIDChanged();
    partial void OnCorrelativoChanging(int value);
    partial void OnCorrelativoChanged();
    partial void OnIdReferenciaChanging(string value);
    partial void OnIdReferenciaChanged();
    #endregion
		
		public CapacitacionCabecera()
		{
			this._CapacitacionAreas = new EntitySet<CapacitacionArea>(new Action<CapacitacionArea>(this.attach_CapacitacionAreas), new Action<CapacitacionArea>(this.detach_CapacitacionAreas));
			this._CapacitacionCapacitadors = new EntitySet<CapacitacionCapacitador>(new Action<CapacitacionCapacitador>(this.attach_CapacitacionCapacitadors), new Action<CapacitacionCapacitador>(this.detach_CapacitacionCapacitadors));
			this._CapacitacionDetalles = new EntitySet<CapacitacionDetalle>(new Action<CapacitacionDetalle>(this.attach_CapacitacionDetalles), new Action<CapacitacionDetalle>(this.detach_CapacitacionDetalles));
			this._CapacitacionFotografias = new EntitySet<CapacitacionFotografia>(new Action<CapacitacionFotografia>(this.attach_CapacitacionFotografias), new Action<CapacitacionFotografia>(this.detach_CapacitacionFotografias));
			this._CapacitacionTemas = new EntitySet<CapacitacionTema>(new Action<CapacitacionTema>(this.attach_CapacitacionTemas), new Action<CapacitacionTema>(this.detach_CapacitacionTemas));
			this._CapacitacionTipo = default(EntityRef<CapacitacionTipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					this.OnCapacitacionIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionID = value;
					this.SendPropertyChanged("CapacitacionID");
					this.OnCapacitacionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionTipoID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionTipoID
		{
			get
			{
				return this._CapacitacionTipoID;
			}
			set
			{
				if ((this._CapacitacionTipoID != value))
				{
					if (this._CapacitacionTipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCapacitacionTipoIDChanging(value);
					this.SendPropertyChanging();
					this._CapacitacionTipoID = value;
					this.SendPropertyChanged("CapacitacionTipoID");
					this.OnCapacitacionTipoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCapacitacion", DbType="SmallDateTime NOT NULL")]
		public System.DateTime FechaCapacitacion
		{
			get
			{
				return this._FechaCapacitacion;
			}
			set
			{
				if ((this._FechaCapacitacion != value))
				{
					this.OnFechaCapacitacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCapacitacion = value;
					this.SendPropertyChanged("FechaCapacitacion");
					this.OnFechaCapacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicación", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ubicación
		{
			get
			{
				return this._Ubicación;
			}
			set
			{
				if ((this._Ubicación != value))
				{
					this.OnUbicaciónChanging(value);
					this.SendPropertyChanging();
					this._Ubicación = value;
					this.SendPropertyChanged("Ubicación");
					this.OnUbicaciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatLong", DbType="VarChar(150)")]
		public string LatLong
		{
			get
			{
				return this._LatLong;
			}
			set
			{
				if ((this._LatLong != value))
				{
					this.OnLatLongChanging(value);
					this.SendPropertyChanging();
					this._LatLong = value;
					this.SendPropertyChanged("LatLong");
					this.OnLatLongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraInicio", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HoraInicio
		{
			get
			{
				return this._HoraInicio;
			}
			set
			{
				if ((this._HoraInicio != value))
				{
					this.OnHoraInicioChanging(value);
					this.SendPropertyChanging();
					this._HoraInicio = value;
					this.SendPropertyChanged("HoraInicio");
					this.OnHoraInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFin", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HoraFin
		{
			get
			{
				return this._HoraFin;
			}
			set
			{
				if ((this._HoraFin != value))
				{
					this.OnHoraFinChanging(value);
					this.SendPropertyChanging();
					this._HoraFin = value;
					this.SendPropertyChanged("HoraFin");
					this.OnHoraFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(MAX)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this.OnObservacionChanging(value);
					this.SendPropertyChanging();
					this._Observacion = value;
					this.SendPropertyChanged("Observacion");
					this.OnObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFRuta", DbType="VarChar(MAX)")]
		public string PDFRuta
		{
			get
			{
				return this._PDFRuta;
			}
			set
			{
				if ((this._PDFRuta != value))
				{
					this.OnPDFRutaChanging(value);
					this.SendPropertyChanging();
					this._PDFRuta = value;
					this.SendPropertyChanged("PDFRuta");
					this.OnPDFRutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFPrint", DbType="Int")]
		public System.Nullable<int> PDFPrint
		{
			get
			{
				return this._PDFPrint;
			}
			set
			{
				if ((this._PDFPrint != value))
				{
					this.OnPDFPrintChanging(value);
					this.SendPropertyChanging();
					this._PDFPrint = value;
					this.SendPropertyChanged("PDFPrint");
					this.OnPDFPrintChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoID", DbType="Char(2)")]
		public string EstadoID
		{
			get
			{
				return this._EstadoID;
			}
			set
			{
				if ((this._EstadoID != value))
				{
					this.OnEstadoIDChanging(value);
					this.SendPropertyChanging();
					this._EstadoID = value;
					this.SendPropertyChanged("EstadoID");
					this.OnEstadoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correlativo", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Correlativo
		{
			get
			{
				return this._Correlativo;
			}
			set
			{
				if ((this._Correlativo != value))
				{
					this.OnCorrelativoChanging(value);
					this.SendPropertyChanging();
					this._Correlativo = value;
					this.SendPropertyChanged("Correlativo");
					this.OnCorrelativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReferencia", DbType="VarChar(17)")]
		public string IdReferencia
		{
			get
			{
				return this._IdReferencia;
			}
			set
			{
				if ((this._IdReferencia != value))
				{
					this.OnIdReferenciaChanging(value);
					this.SendPropertyChanging();
					this._IdReferencia = value;
					this.SendPropertyChanged("IdReferencia");
					this.OnIdReferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionArea", Storage="_CapacitacionAreas", ThisKey="CapacitacionID", OtherKey="CapacitacionID")]
		public EntitySet<CapacitacionArea> CapacitacionAreas
		{
			get
			{
				return this._CapacitacionAreas;
			}
			set
			{
				this._CapacitacionAreas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionCapacitador", Storage="_CapacitacionCapacitadors", ThisKey="CapacitacionID", OtherKey="CapacitacionID")]
		public EntitySet<CapacitacionCapacitador> CapacitacionCapacitadors
		{
			get
			{
				return this._CapacitacionCapacitadors;
			}
			set
			{
				this._CapacitacionCapacitadors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionDetalle", Storage="_CapacitacionDetalles", ThisKey="CapacitacionID", OtherKey="CapacitacionID")]
		public EntitySet<CapacitacionDetalle> CapacitacionDetalles
		{
			get
			{
				return this._CapacitacionDetalles;
			}
			set
			{
				this._CapacitacionDetalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionFotografia", Storage="_CapacitacionFotografias", ThisKey="CapacitacionID", OtherKey="CapacitacionID")]
		public EntitySet<CapacitacionFotografia> CapacitacionFotografias
		{
			get
			{
				return this._CapacitacionFotografias;
			}
			set
			{
				this._CapacitacionFotografias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionCabecera_CapacitacionTema", Storage="_CapacitacionTemas", ThisKey="CapacitacionID", OtherKey="CapacitacionID")]
		public EntitySet<CapacitacionTema> CapacitacionTemas
		{
			get
			{
				return this._CapacitacionTemas;
			}
			set
			{
				this._CapacitacionTemas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CapacitacionTipo_CapacitacionCabecera", Storage="_CapacitacionTipo", ThisKey="CapacitacionTipoID", OtherKey="CapacitacionTipoID", IsForeignKey=true)]
		public CapacitacionTipo CapacitacionTipo
		{
			get
			{
				return this._CapacitacionTipo.Entity;
			}
			set
			{
				CapacitacionTipo previousValue = this._CapacitacionTipo.Entity;
				if (((previousValue != value) 
							|| (this._CapacitacionTipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CapacitacionTipo.Entity = null;
						previousValue.CapacitacionCabeceras.Remove(this);
					}
					this._CapacitacionTipo.Entity = value;
					if ((value != null))
					{
						value.CapacitacionCabeceras.Add(this);
						this._CapacitacionTipoID = value.CapacitacionTipoID;
					}
					else
					{
						this._CapacitacionTipoID = default(string);
					}
					this.SendPropertyChanged("CapacitacionTipo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CapacitacionAreas(CapacitacionArea entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = this;
		}
		
		private void detach_CapacitacionAreas(CapacitacionArea entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = null;
		}
		
		private void attach_CapacitacionCapacitadors(CapacitacionCapacitador entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = this;
		}
		
		private void detach_CapacitacionCapacitadors(CapacitacionCapacitador entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = null;
		}
		
		private void attach_CapacitacionDetalles(CapacitacionDetalle entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = this;
		}
		
		private void detach_CapacitacionDetalles(CapacitacionDetalle entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = null;
		}
		
		private void attach_CapacitacionFotografias(CapacitacionFotografia entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = this;
		}
		
		private void detach_CapacitacionFotografias(CapacitacionFotografia entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = null;
		}
		
		private void attach_CapacitacionTemas(CapacitacionTema entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = this;
		}
		
		private void detach_CapacitacionTemas(CapacitacionTema entity)
		{
			this.SendPropertyChanging();
			entity.CapacitacionCabecera = null;
		}
	}
	
	public partial class SAS_ListadoTemasParaCapacitacionByTemaIdResult
	{
		
		private int _TemaAreaId;
		
		private string _TemaID;
		
		private string _AreaID;
		
		private byte _Estado;
		
		private string _Area;
		
		private string _Tema;
		
		public SAS_ListadoTemasParaCapacitacionByTemaIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaAreaId", DbType="Int NOT NULL")]
		public int TemaAreaId
		{
			get
			{
				return this._TemaAreaId;
			}
			set
			{
				if ((this._TemaAreaId != value))
				{
					this._TemaAreaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string TemaID
		{
			get
			{
				return this._TemaID;
			}
			set
			{
				if ((this._TemaID != value))
				{
					this._TemaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaID", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string AreaID
		{
			get
			{
				return this._AreaID;
			}
			set
			{
				if ((this._AreaID != value))
				{
					this._AreaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt NOT NULL")]
		public byte Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(100)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tema", DbType="VarChar(150)")]
		public string Tema
		{
			get
			{
				return this._Tema;
			}
			set
			{
				if ((this._Tema != value))
				{
					this._Tema = value;
				}
			}
		}
	}
	
	public partial class ListadoRegistroCapacitacionesPorPeriodoResult
	{
		
		private string _Folio;
		
		private string _CapacitacionID;
		
		private string _CapacitacionTipoID;
		
		private string _Capacitacion;
		
		private System.DateTime _FechaCapacitacion;
		
		private string _Ubicación;
		
		private string _LatLong;
		
		private System.Nullable<System.DateTime> _HoraInicio;
		
		private System.Nullable<System.DateTime> _HoraFin;
		
		private string _Observacion;
		
		private System.DateTime _FechaRegistro;
		
		private string _PDFRuta;
		
		private System.Nullable<int> _PDFPrint;
		
		private string _EstadoID;
		
		private string _Estado;
		
		private string _CapacitacionID1;
		
		private string _TemaID;
		
		private string _TemaI;
		
		private System.Nullable<byte> _TemaEstado;
		
		private System.Nullable<int> _Asistentes;
		
		private string _AreaId;
		
		private string _Area;
		
		private System.Nullable<int> _Capacitadores;
		
		private System.Nullable<int> _Duracion;
		
		public ListadoRegistroCapacitacionesPorPeriodoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folio", DbType="VarChar(7)")]
		public string Folio
		{
			get
			{
				return this._Folio;
			}
			set
			{
				if ((this._Folio != value))
				{
					this._Folio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					this._CapacitacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionTipoID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionTipoID
		{
			get
			{
				return this._CapacitacionTipoID;
			}
			set
			{
				if ((this._CapacitacionTipoID != value))
				{
					this._CapacitacionTipoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacitacion", DbType="VarChar(150)")]
		public string Capacitacion
		{
			get
			{
				return this._Capacitacion;
			}
			set
			{
				if ((this._Capacitacion != value))
				{
					this._Capacitacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCapacitacion", DbType="SmallDateTime NOT NULL")]
		public System.DateTime FechaCapacitacion
		{
			get
			{
				return this._FechaCapacitacion;
			}
			set
			{
				if ((this._FechaCapacitacion != value))
				{
					this._FechaCapacitacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicación", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ubicación
		{
			get
			{
				return this._Ubicación;
			}
			set
			{
				if ((this._Ubicación != value))
				{
					this._Ubicación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatLong", DbType="VarChar(150)")]
		public string LatLong
		{
			get
			{
				return this._LatLong;
			}
			set
			{
				if ((this._LatLong != value))
				{
					this._LatLong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraInicio", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HoraInicio
		{
			get
			{
				return this._HoraInicio;
			}
			set
			{
				if ((this._HoraInicio != value))
				{
					this._HoraInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFin", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HoraFin
		{
			get
			{
				return this._HoraFin;
			}
			set
			{
				if ((this._HoraFin != value))
				{
					this._HoraFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(MAX)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFRuta", DbType="VarChar(MAX)")]
		public string PDFRuta
		{
			get
			{
				return this._PDFRuta;
			}
			set
			{
				if ((this._PDFRuta != value))
				{
					this._PDFRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFPrint", DbType="Int")]
		public System.Nullable<int> PDFPrint
		{
			get
			{
				return this._PDFPrint;
			}
			set
			{
				if ((this._PDFPrint != value))
				{
					this._PDFPrint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoID", DbType="Char(2)")]
		public string EstadoID
		{
			get
			{
				return this._EstadoID;
			}
			set
			{
				if ((this._EstadoID != value))
				{
					this._EstadoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID1", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID1
		{
			get
			{
				return this._CapacitacionID1;
			}
			set
			{
				if ((this._CapacitacionID1 != value))
				{
					this._CapacitacionID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string TemaID
		{
			get
			{
				return this._TemaID;
			}
			set
			{
				if ((this._TemaID != value))
				{
					this._TemaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaI", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string TemaI
		{
			get
			{
				return this._TemaI;
			}
			set
			{
				if ((this._TemaI != value))
				{
					this._TemaI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemaEstado", DbType="TinyInt")]
		public System.Nullable<byte> TemaEstado
		{
			get
			{
				return this._TemaEstado;
			}
			set
			{
				if ((this._TemaEstado != value))
				{
					this._TemaEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asistentes", DbType="Int")]
		public System.Nullable<int> Asistentes
		{
			get
			{
				return this._Asistentes;
			}
			set
			{
				if ((this._Asistentes != value))
				{
					this._Asistentes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaId", DbType="Char(3)")]
		public string AreaId
		{
			get
			{
				return this._AreaId;
			}
			set
			{
				if ((this._AreaId != value))
				{
					this._AreaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(100)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacitadores", DbType="Int")]
		public System.Nullable<int> Capacitadores
		{
			get
			{
				return this._Capacitadores;
			}
			set
			{
				if ((this._Capacitadores != value))
				{
					this._Capacitadores = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duracion", DbType="Int")]
		public System.Nullable<int> Duracion
		{
			get
			{
				return this._Duracion;
			}
			set
			{
				if ((this._Duracion != value))
				{
					this._Duracion = value;
				}
			}
		}
	}
	
	public partial class ListadoRegistroCapacitacionesPorIDResult
	{
		
		private string _Folio;
		
		private string _CapacitacionID;
		
		private string _CapacitacionTipoID;
		
		private string _Capacitacion;
		
		private System.DateTime _FechaCapacitacion;
		
		private string _Ubicación;
		
		private string _LatLong;
		
		private System.Nullable<System.DateTime> _HoraInicio;
		
		private System.Nullable<System.DateTime> _HoraFin;
		
		private string _Observacion;
		
		private System.DateTime _FechaRegistro;
		
		private string _PDFRuta;
		
		private System.Nullable<int> _PDFPrint;
		
		private string _EstadoID;
		
		private string _Estado;
		
		private System.Nullable<int> _Duracion;
		
		private string _ReferenciaID;
		
		public ListadoRegistroCapacitacionesPorIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folio", DbType="VarChar(7)")]
		public string Folio
		{
			get
			{
				return this._Folio;
			}
			set
			{
				if ((this._Folio != value))
				{
					this._Folio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionID
		{
			get
			{
				return this._CapacitacionID;
			}
			set
			{
				if ((this._CapacitacionID != value))
				{
					this._CapacitacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapacitacionTipoID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CapacitacionTipoID
		{
			get
			{
				return this._CapacitacionTipoID;
			}
			set
			{
				if ((this._CapacitacionTipoID != value))
				{
					this._CapacitacionTipoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacitacion", DbType="VarChar(150)")]
		public string Capacitacion
		{
			get
			{
				return this._Capacitacion;
			}
			set
			{
				if ((this._Capacitacion != value))
				{
					this._Capacitacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCapacitacion", DbType="SmallDateTime NOT NULL")]
		public System.DateTime FechaCapacitacion
		{
			get
			{
				return this._FechaCapacitacion;
			}
			set
			{
				if ((this._FechaCapacitacion != value))
				{
					this._FechaCapacitacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicación", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ubicación
		{
			get
			{
				return this._Ubicación;
			}
			set
			{
				if ((this._Ubicación != value))
				{
					this._Ubicación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatLong", DbType="VarChar(150)")]
		public string LatLong
		{
			get
			{
				return this._LatLong;
			}
			set
			{
				if ((this._LatLong != value))
				{
					this._LatLong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraInicio", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HoraInicio
		{
			get
			{
				return this._HoraInicio;
			}
			set
			{
				if ((this._HoraInicio != value))
				{
					this._HoraInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraFin", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HoraFin
		{
			get
			{
				return this._HoraFin;
			}
			set
			{
				if ((this._HoraFin != value))
				{
					this._HoraFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(MAX)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFRuta", DbType="VarChar(MAX)")]
		public string PDFRuta
		{
			get
			{
				return this._PDFRuta;
			}
			set
			{
				if ((this._PDFRuta != value))
				{
					this._PDFRuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFPrint", DbType="Int")]
		public System.Nullable<int> PDFPrint
		{
			get
			{
				return this._PDFPrint;
			}
			set
			{
				if ((this._PDFPrint != value))
				{
					this._PDFPrint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoID", DbType="Char(2)")]
		public string EstadoID
		{
			get
			{
				return this._EstadoID;
			}
			set
			{
				if ((this._EstadoID != value))
				{
					this._EstadoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duracion", DbType="Int")]
		public System.Nullable<int> Duracion
		{
			get
			{
				return this._Duracion;
			}
			set
			{
				if ((this._Duracion != value))
				{
					this._Duracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenciaID", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string ReferenciaID
		{
			get
			{
				return this._ReferenciaID;
			}
			set
			{
				if ((this._ReferenciaID != value))
				{
					this._ReferenciaID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
