<?xml version="1.0" encoding="utf-8"?><Database Name="SATURNO" Class="ITDContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.140.7;Initial Catalog=SATURNO;Persist Security Info=True;User ID=eaurazo" SettingsObjectName="Asistencia.Datos.Properties.Settings" SettingsPropertyName="SATURNOConnectionString8" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SAS_DispositivoImagenes" Member="SAS_DispositivoImagenes">
    <Type Name="SAS_DispositivoImagene">
      <Column Name="DispositivoId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Item" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EsPrincipal" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ruta" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Longitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nota" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SAS_EsPropioCBO" Method="SAS_EsPropioCBO">
    <ElementType Name="SAS_EsPropioCBOResult">
      <Column Name="codigo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_EstadoDispositivoCBO" Method="SAS_EstadoDispositivoCBO">
    <ElementType Name="SAS_EstadoDispositivoCBOResult">
      <Column Name="codigo" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_FuncionamientoDispositivoCBO" Method="SAS_FuncionamientoDispositivoCBO">
    <ElementType Name="SAS_FuncionamientoDispositivoCBOResult">
      <Column Name="codigo" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_MarcaDispositivoCBO" Method="SAS_MarcaDispositivoCBO">
    <ElementType Name="SAS_MarcaDispositivoCBOResult">
      <Column Name="codigo" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_ModeloDispositivoCBO" Method="SAS_ModeloDispositivoCBO">
    <ElementType Name="SAS_ModeloDispositivoCBOResult">
      <Column Name="codigo" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_ProveedorDispositivoCBO" Method="SAS_ProveedorDispositivoCBO">
    <ElementType Name="SAS_ProveedorDispositivoCBOResult">
      <Column Name="codigo" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_SedeDispositivoCBO" Method="SAS_SedeDispositivoCBO">
    <ElementType Name="SAS_SedeDispositivoCBOResult">
      <Column Name="codigo" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_TipoDispositivoCBO" Method="SAS_TipoDispositivoCBO">
    <ElementType Name="SAS_TipoDispositivoCBOResult">
      <Column Name="codigo" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SAS_ListadoDeDispositivosAll" Method="SAS_ListadoDeDispositivosAll">
    <ElementType Name="SAS_ListadoDeDispositivosAllResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitud" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dispositivo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sedeCodigo" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="sedeDescripcion" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="numeroSerie" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="caracteristicas" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="idestado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="tipoDispositivoCodigo" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="tipoDispositivo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="item" Type="System.String" DbType="VarChar(2512) NOT NULL" CanBeNull="false" />
      <Column Name="codigoSegmentoIP" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="numeroIP" Type="System.String" DbType="VarChar(132) NOT NULL" CanBeNull="false" />
      <Column Name="creadoPor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fechacreacion" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="activoCodigoERP" Type="System.String" DbType="VarChar(22)" CanBeNull="true" />
      <Column Name="activo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IdDispostivoColor" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="color" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="idModelo" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="MODELO" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="idMarca" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="numeroParte" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadoProducto" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="estadoProducto" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EsPropio" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AlquiladoPropio" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="idProducto" Type="System.String" DbType="VarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="producto" Type="System.String" DbType="VarChar(240) NOT NULL" CanBeNull="false" />
      <Column Name="rutaImagen" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="funcionamientoCodigo" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="funcionamiento" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="idClieprov" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="razonSocial" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="coordenada" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fechaActivacion" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="idCobrarpagarDoc" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="documentoCompra" Type="System.String" DbType="VarChar(54) NOT NULL" CanBeNull="false" />
      <Column Name="fechaBaja" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="fechaProduccion" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="esFinal" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="registro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistradoNoRegistrado" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="idarea" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="area" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="lineaCelular" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="planDeTelefonia" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="costoUSD" Type="System.Decimal" DbType="Decimal(12,3) NOT NULL" CanBeNull="false" />
      <Column Name="ubicacion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AniosParaDepreciar" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="idSistemaDeImpresion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sistemaDeImpresion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ContabilizacionDeRegistro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="costoMantenimientoAnualUSD" Type="System.Decimal" DbType="Decimal(12,3) NOT NULL" CanBeNull="false" />
      <Column Name="costoSuministroAnualUSD" Type="System.Decimal" DbType="Decimal(12,3) NOT NULL" CanBeNull="false" />
      <Column Name="kilovatioHora" Type="System.Decimal" DbType="Decimal(12,3) NOT NULL" CanBeNull="false" />
      <Column Name="tipoDeFacturacionDeConsumoEnergetico" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="idcodigoGeneral" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="ColaboradorUnicoAsociado" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>