#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SATURNO")]
	public partial class ProduccionContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSAS_ConformacionDeCarga(SAS_ConformacionDeCarga instance);
    partial void UpdateSAS_ConformacionDeCarga(SAS_ConformacionDeCarga instance);
    partial void DeleteSAS_ConformacionDeCarga(SAS_ConformacionDeCarga instance);
    partial void InsertSAS_ConformacionDeCargaDetalle(SAS_ConformacionDeCargaDetalle instance);
    partial void UpdateSAS_ConformacionDeCargaDetalle(SAS_ConformacionDeCargaDetalle instance);
    partial void DeleteSAS_ConformacionDeCargaDetalle(SAS_ConformacionDeCargaDetalle instance);
    #endregion
		
		public ProduccionContextDataContext() : 
				base(global::Asistencia.Datos.Properties.Settings.Default.SATURNOConnectionString7, mappingSource)
		{
			OnCreated();
		}
		
		public ProduccionContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProduccionContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProduccionContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProduccionContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SAS_ConformacionDeCarga> SAS_ConformacionDeCargas
		{
			get
			{
				return this.GetTable<SAS_ConformacionDeCarga>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ConformacionDeCargaDetalle> SAS_ConformacionDeCargaDetalles
		{
			get
			{
				return this.GetTable<SAS_ConformacionDeCargaDetalle>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ConformacionDeCargaDetalleByIdByPalleta> SAS_ConformacionDeCargaDetalleByIdByPalletas
		{
			get
			{
				return this.GetTable<SAS_ConformacionDeCargaDetalleByIdByPalleta>();
			}
		}
		
		public System.Data.Linq.Table<SAS_ListadoConformacionDeCargaPBI> SAS_ListadoConformacionDeCargaPBIs
		{
			get
			{
				return this.GetTable<SAS_ListadoConformacionDeCargaPBI>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoConformacionDeCargaByPeriodo")]
		public ISingleResult<SAS_ListadoConformacionDeCargaByPeriodoResult> SAS_ListadoConformacionDeCargaByPeriodo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string hasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta);
			return ((ISingleResult<SAS_ListadoConformacionDeCargaByPeriodoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ConformacionDeCargaByDate")]
		public ISingleResult<SAS_ConformacionDeCargaByDateResult> SAS_ConformacionDeCargaByDate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string hasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta);
			return ((ISingleResult<SAS_ConformacionDeCargaByDateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoConformidadCargaByBooking")]
		public ISingleResult<SAS_ListadoConformidadCargaByBookingResult> SAS_ListadoConformidadCargaByBooking([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Booking", DbType="VarChar(20)")] string booking)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), booking);
			return ((ISingleResult<SAS_ListadoConformidadCargaByBookingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoPaletasDisponiblesParaConformacionDeCarga")]
		public ISingleResult<SAS_ListadoPaletasDisponiblesParaConformacionDeCargaResult> SAS_ListadoPaletasDisponiblesParaConformacionDeCarga([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCampana", DbType="VarChar(4)")] string idCampana)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCampana);
			return ((ISingleResult<SAS_ListadoPaletasDisponiblesParaConformacionDeCargaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoConformacionDeCargaPBIById")]
		public ISingleResult<SAS_ListadoConformacionDeCargaPBIByIdResult> SAS_ListadoConformacionDeCargaPBIById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<SAS_ListadoConformacionDeCargaPBIByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SAS_ListadoConformacionDeCargaDisponiblesByIdCliente")]
		public ISingleResult<SAS_ListadoConformacionDeCargaDisponiblesByIdClienteResult> SAS_ListadoConformacionDeCargaDisponiblesByIdCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClienteId", DbType="VarChar(20)")] string clienteId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clienteId);
			return ((ISingleResult<SAS_ListadoConformacionDeCargaDisponiblesByIdClienteResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ConformacionDeCarga")]
	public partial class SAS_ConformacionDeCarga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _Fecha;
		
		private string _Descripcion;
		
		private string _NumeroContenedor;
		
		private string _Booking;
		
		private string _Observacion;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private string _UserId;
		
		private string _Hostname;
		
		private string _EstadoId;
		
		private string _idCampania;
		
		private string _IdClieprov;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnNumeroContenedorChanging(string value);
    partial void OnNumeroContenedorChanged();
    partial void OnBookingChanging(string value);
    partial void OnBookingChanged();
    partial void OnObservacionChanging(string value);
    partial void OnObservacionChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnHostnameChanging(string value);
    partial void OnHostnameChanged();
    partial void OnEstadoIdChanging(string value);
    partial void OnEstadoIdChanged();
    partial void OnidCampaniaChanging(string value);
    partial void OnidCampaniaChanged();
    partial void OnIdClieprovChanging(string value);
    partial void OnIdClieprovChanged();
    #endregion
		
		public SAS_ConformacionDeCarga()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroContenedor", DbType="VarChar(20)")]
		public string NumeroContenedor
		{
			get
			{
				return this._NumeroContenedor;
			}
			set
			{
				if ((this._NumeroContenedor != value))
				{
					this.OnNumeroContenedorChanging(value);
					this.SendPropertyChanging();
					this._NumeroContenedor = value;
					this.SendPropertyChanged("NumeroContenedor");
					this.OnNumeroContenedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Booking
		{
			get
			{
				return this._Booking;
			}
			set
			{
				if ((this._Booking != value))
				{
					this.OnBookingChanging(value);
					this.SendPropertyChanging();
					this._Booking = value;
					this.SendPropertyChanged("Booking");
					this.OnBookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this.OnObservacionChanging(value);
					this.SendPropertyChanging();
					this._Observacion = value;
					this.SendPropertyChanged("Observacion");
					this.OnObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(25)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname", DbType="VarChar(50)")]
		public string Hostname
		{
			get
			{
				return this._Hostname;
			}
			set
			{
				if ((this._Hostname != value))
				{
					this.OnHostnameChanging(value);
					this.SendPropertyChanging();
					this._Hostname = value;
					this.SendPropertyChanged("Hostname");
					this.OnHostnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoId", DbType="Char(2)")]
		public string EstadoId
		{
			get
			{
				return this._EstadoId;
			}
			set
			{
				if ((this._EstadoId != value))
				{
					this.OnEstadoIdChanging(value);
					this.SendPropertyChanging();
					this._EstadoId = value;
					this.SendPropertyChanged("EstadoId");
					this.OnEstadoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCampania", DbType="Char(4)")]
		public string idCampania
		{
			get
			{
				return this._idCampania;
			}
			set
			{
				if ((this._idCampania != value))
				{
					this.OnidCampaniaChanging(value);
					this.SendPropertyChanging();
					this._idCampania = value;
					this.SendPropertyChanged("idCampania");
					this.OnidCampaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClieprov", DbType="VarChar(14)")]
		public string IdClieprov
		{
			get
			{
				return this._IdClieprov;
			}
			set
			{
				if ((this._IdClieprov != value))
				{
					this.OnIdClieprovChanging(value);
					this.SendPropertyChanging();
					this._IdClieprov = value;
					this.SendPropertyChanged("IdClieprov");
					this.OnIdClieprovChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ConformacionDeCargaDetalle")]
	public partial class SAS_ConformacionDeCargaDetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdConformacionCarga;
		
		private int _Id;
		
		private string _IdRegistroPaleta;
		
		private System.Nullable<byte> _Estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdConformacionCargaChanging(int value);
    partial void OnIdConformacionCargaChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdRegistroPaletaChanging(string value);
    partial void OnIdRegistroPaletaChanged();
    partial void OnEstadoChanging(System.Nullable<byte> value);
    partial void OnEstadoChanged();
    #endregion
		
		public SAS_ConformacionDeCargaDetalle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConformacionCarga", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdConformacionCarga
		{
			get
			{
				return this._IdConformacionCarga;
			}
			set
			{
				if ((this._IdConformacionCarga != value))
				{
					this.OnIdConformacionCargaChanging(value);
					this.SendPropertyChanging();
					this._IdConformacionCarga = value;
					this.SendPropertyChanged("IdConformacionCarga");
					this.OnIdConformacionCargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroPaleta", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string IdRegistroPaleta
		{
			get
			{
				return this._IdRegistroPaleta;
			}
			set
			{
				if ((this._IdRegistroPaleta != value))
				{
					this.OnIdRegistroPaletaChanging(value);
					this.SendPropertyChanging();
					this._IdRegistroPaleta = value;
					this.SendPropertyChanged("IdRegistroPaleta");
					this.OnIdRegistroPaletaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="TinyInt")]
		public System.Nullable<byte> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ConformacionDeCargaDetalleByIdByPalleta")]
	public partial class SAS_ConformacionDeCargaDetalleByIdByPalleta
	{
		
		private int _IdConformacionCarga;
		
		private string _IdRegistroPaleta;
		
		public SAS_ConformacionDeCargaDetalleByIdByPalleta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConformacionCarga", DbType="Int NOT NULL")]
		public int IdConformacionCarga
		{
			get
			{
				return this._IdConformacionCarga;
			}
			set
			{
				if ((this._IdConformacionCarga != value))
				{
					this._IdConformacionCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroPaleta", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string IdRegistroPaleta
		{
			get
			{
				return this._IdRegistroPaleta;
			}
			set
			{
				if ((this._IdRegistroPaleta != value))
				{
					this._IdRegistroPaleta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAS_ListadoConformacionDeCargaPBI")]
	public partial class SAS_ListadoConformacionDeCargaPBI
	{
		
		private System.Nullable<int> _Semana;
		
		private int _ConformacionCargaId;
		
		private System.DateTime _ConformacionCargaFecha;
		
		private string _ConformacionCarga;
		
		private string _NumeroContenedor;
		
		private string _Booking;
		
		private string _NumeroPackingList;
		
		private string _Observacion;
		
		private string _CampaniaId;
		
		private string _EstadoId;
		
		private string _EstadoConformidadCarga;
		
		private string _Campania;
		
		private System.Nullable<int> _Id;
		
		private string _IdRegistroPaleta;
		
		private string _NumeroPaleta;
		
		private string _TipoDePaletaId;
		
		private string _TipoDePaleta;
		
		private string _ClienteId;
		
		private string _Cliente;
		
		private string _GrowerCode;
		
		private System.Nullable<byte> _EstadoDetalle;
		
		private string _CultivoId;
		
		private string _Cultivo;
		
		private string _VariedadId;
		
		private string _Variedad;
		
		private string _EnvaseId;
		
		private string _Envase;
		
		private string _CategoriaId;
		
		private string _Categoria;
		
		private string _CalibreId;
		
		private string _Calibre;
		
		private string _ColorId;
		
		private string _Color;
		
		private string _PahiruelaId;
		
		private string _Pahiruela;
		
		private string _FechaProduccion;
		
		private System.Nullable<decimal> _CantidadCajas;
		
		private string _PaletaOrigen;
		
		private string _traza;
		
		private System.Nullable<decimal> _pesoReferencial;
		
		private string _EmbalajeId;
		
		private string _Embalaje;
		
		public SAS_ListadoConformacionDeCargaPBI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semana", DbType="Int")]
		public System.Nullable<int> Semana
		{
			get
			{
				return this._Semana;
			}
			set
			{
				if ((this._Semana != value))
				{
					this._Semana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConformacionCargaId", DbType="Int NOT NULL")]
		public int ConformacionCargaId
		{
			get
			{
				return this._ConformacionCargaId;
			}
			set
			{
				if ((this._ConformacionCargaId != value))
				{
					this._ConformacionCargaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConformacionCargaFecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime ConformacionCargaFecha
		{
			get
			{
				return this._ConformacionCargaFecha;
			}
			set
			{
				if ((this._ConformacionCargaFecha != value))
				{
					this._ConformacionCargaFecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConformacionCarga", DbType="VarChar(250)")]
		public string ConformacionCarga
		{
			get
			{
				return this._ConformacionCarga;
			}
			set
			{
				if ((this._ConformacionCarga != value))
				{
					this._ConformacionCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroContenedor", DbType="VarChar(20)")]
		public string NumeroContenedor
		{
			get
			{
				return this._NumeroContenedor;
			}
			set
			{
				if ((this._NumeroContenedor != value))
				{
					this._NumeroContenedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Booking
		{
			get
			{
				return this._Booking;
			}
			set
			{
				if ((this._Booking != value))
				{
					this._Booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPackingList", DbType="VarChar(30)")]
		public string NumeroPackingList
		{
			get
			{
				return this._NumeroPackingList;
			}
			set
			{
				if ((this._NumeroPackingList != value))
				{
					this._NumeroPackingList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampaniaId", DbType="Char(4)")]
		public string CampaniaId
		{
			get
			{
				return this._CampaniaId;
			}
			set
			{
				if ((this._CampaniaId != value))
				{
					this._CampaniaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoId", DbType="Char(2)")]
		public string EstadoId
		{
			get
			{
				return this._EstadoId;
			}
			set
			{
				if ((this._EstadoId != value))
				{
					this._EstadoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoConformidadCarga", DbType="VarChar(30)")]
		public string EstadoConformidadCarga
		{
			get
			{
				return this._EstadoConformidadCarga;
			}
			set
			{
				if ((this._EstadoConformidadCarga != value))
				{
					this._EstadoConformidadCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campania", DbType="VarChar(100)")]
		public string Campania
		{
			get
			{
				return this._Campania;
			}
			set
			{
				if ((this._Campania != value))
				{
					this._Campania = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroPaleta", DbType="VarChar(19)")]
		public string IdRegistroPaleta
		{
			get
			{
				return this._IdRegistroPaleta;
			}
			set
			{
				if ((this._IdRegistroPaleta != value))
				{
					this._IdRegistroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPaleta", DbType="VarChar(20)")]
		public string NumeroPaleta
		{
			get
			{
				return this._NumeroPaleta;
			}
			set
			{
				if ((this._NumeroPaleta != value))
				{
					this._NumeroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaletaId", DbType="Char(3)")]
		public string TipoDePaletaId
		{
			get
			{
				return this._TipoDePaletaId;
			}
			set
			{
				if ((this._TipoDePaletaId != value))
				{
					this._TipoDePaletaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaleta", DbType="VarChar(50)")]
		public string TipoDePaleta
		{
			get
			{
				return this._TipoDePaleta;
			}
			set
			{
				if ((this._TipoDePaleta != value))
				{
					this._TipoDePaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteId", DbType="Char(11)")]
		public string ClienteId
		{
			get
			{
				return this._ClienteId;
			}
			set
			{
				if ((this._ClienteId != value))
				{
					this._ClienteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(200)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowerCode", DbType="VarChar(8000)")]
		public string GrowerCode
		{
			get
			{
				return this._GrowerCode;
			}
			set
			{
				if ((this._GrowerCode != value))
				{
					this._GrowerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoDetalle", DbType="TinyInt")]
		public System.Nullable<byte> EstadoDetalle
		{
			get
			{
				return this._EstadoDetalle;
			}
			set
			{
				if ((this._EstadoDetalle != value))
				{
					this._EstadoDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CultivoId", DbType="Char(4)")]
		public string CultivoId
		{
			get
			{
				return this._CultivoId;
			}
			set
			{
				if ((this._CultivoId != value))
				{
					this._CultivoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cultivo", DbType="VarChar(50)")]
		public string Cultivo
		{
			get
			{
				return this._Cultivo;
			}
			set
			{
				if ((this._Cultivo != value))
				{
					this._Cultivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariedadId", DbType="Char(3)")]
		public string VariedadId
		{
			get
			{
				return this._VariedadId;
			}
			set
			{
				if ((this._VariedadId != value))
				{
					this._VariedadId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variedad", DbType="VarChar(80)")]
		public string Variedad
		{
			get
			{
				return this._Variedad;
			}
			set
			{
				if ((this._Variedad != value))
				{
					this._Variedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvaseId", DbType="Char(3)")]
		public string EnvaseId
		{
			get
			{
				return this._EnvaseId;
			}
			set
			{
				if ((this._EnvaseId != value))
				{
					this._EnvaseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Envase", DbType="VarChar(12)")]
		public string Envase
		{
			get
			{
				return this._Envase;
			}
			set
			{
				if ((this._Envase != value))
				{
					this._Envase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaId", DbType="Char(3)")]
		public string CategoriaId
		{
			get
			{
				return this._CategoriaId;
			}
			set
			{
				if ((this._CategoriaId != value))
				{
					this._CategoriaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(10)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalibreId", DbType="Char(6)")]
		public string CalibreId
		{
			get
			{
				return this._CalibreId;
			}
			set
			{
				if ((this._CalibreId != value))
				{
					this._CalibreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calibre", DbType="VarChar(10)")]
		public string Calibre
		{
			get
			{
				return this._Calibre;
			}
			set
			{
				if ((this._Calibre != value))
				{
					this._Calibre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorId", DbType="VarChar(3)")]
		public string ColorId
		{
			get
			{
				return this._ColorId;
			}
			set
			{
				if ((this._ColorId != value))
				{
					this._ColorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(10)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PahiruelaId", DbType="VarChar(3)")]
		public string PahiruelaId
		{
			get
			{
				return this._PahiruelaId;
			}
			set
			{
				if ((this._PahiruelaId != value))
				{
					this._PahiruelaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pahiruela", DbType="VarChar(100)")]
		public string Pahiruela
		{
			get
			{
				return this._Pahiruela;
			}
			set
			{
				if ((this._Pahiruela != value))
				{
					this._Pahiruela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProduccion", DbType="VarChar(8000)")]
		public string FechaProduccion
		{
			get
			{
				return this._FechaProduccion;
			}
			set
			{
				if ((this._FechaProduccion != value))
				{
					this._FechaProduccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadCajas", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CantidadCajas
		{
			get
			{
				return this._CantidadCajas;
			}
			set
			{
				if ((this._CantidadCajas != value))
				{
					this._CantidadCajas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaletaOrigen", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string PaletaOrigen
		{
			get
			{
				return this._PaletaOrigen;
			}
			set
			{
				if ((this._PaletaOrigen != value))
				{
					this._PaletaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traza", DbType="VarChar(8000)")]
		public string traza
		{
			get
			{
				return this._traza;
			}
			set
			{
				if ((this._traza != value))
				{
					this._traza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoReferencial", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> pesoReferencial
		{
			get
			{
				return this._pesoReferencial;
			}
			set
			{
				if ((this._pesoReferencial != value))
				{
					this._pesoReferencial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmbalajeId", DbType="Char(10)")]
		public string EmbalajeId
		{
			get
			{
				return this._EmbalajeId;
			}
			set
			{
				if ((this._EmbalajeId != value))
				{
					this._EmbalajeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Embalaje", DbType="VarChar(20)")]
		public string Embalaje
		{
			get
			{
				return this._Embalaje;
			}
			set
			{
				if ((this._Embalaje != value))
				{
					this._Embalaje = value;
				}
			}
		}
	}
	
	public partial class SAS_ListadoConformacionDeCargaByPeriodoResult
	{
		
		private int _Id;
		
		private System.DateTime _Fecha;
		
		private string _Descripcion;
		
		private string _NumeroContenedor;
		
		private string _Booking;
		
		private string _Observacion;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private string _UserId;
		
		private string _Hostname;
		
		private string _EstadoId;
		
		private string _Estado;
		
		private string _idCampania;
		
		private string _IdClieprov;
		
		private string _Cliente;
		
		public SAS_ListadoConformacionDeCargaByPeriodoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroContenedor", DbType="VarChar(20)")]
		public string NumeroContenedor
		{
			get
			{
				return this._NumeroContenedor;
			}
			set
			{
				if ((this._NumeroContenedor != value))
				{
					this._NumeroContenedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Booking
		{
			get
			{
				return this._Booking;
			}
			set
			{
				if ((this._Booking != value))
				{
					this._Booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(25)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname", DbType="VarChar(50)")]
		public string Hostname
		{
			get
			{
				return this._Hostname;
			}
			set
			{
				if ((this._Hostname != value))
				{
					this._Hostname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoId", DbType="Char(2)")]
		public string EstadoId
		{
			get
			{
				return this._EstadoId;
			}
			set
			{
				if ((this._EstadoId != value))
				{
					this._EstadoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(30)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCampania", DbType="Char(4)")]
		public string idCampania
		{
			get
			{
				return this._idCampania;
			}
			set
			{
				if ((this._idCampania != value))
				{
					this._idCampania = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClieprov", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string IdClieprov
		{
			get
			{
				return this._IdClieprov;
			}
			set
			{
				if ((this._IdClieprov != value))
				{
					this._IdClieprov = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(200)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
	}
	
	public partial class SAS_ConformacionDeCargaByDateResult
	{
		
		private int _Id;
		
		private System.DateTime _Fecha;
		
		private string _Descripcion;
		
		private string _NumeroContenedor;
		
		private string _Booking;
		
		private string _Observacion;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private string _UserId;
		
		private string _Hostname;
		
		private string _EstadoId;
		
		private string _idCampania;
		
		private string _NumeroPackingList;
		
		public SAS_ConformacionDeCargaByDateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroContenedor", DbType="VarChar(20)")]
		public string NumeroContenedor
		{
			get
			{
				return this._NumeroContenedor;
			}
			set
			{
				if ((this._NumeroContenedor != value))
				{
					this._NumeroContenedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Booking
		{
			get
			{
				return this._Booking;
			}
			set
			{
				if ((this._Booking != value))
				{
					this._Booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(25)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hostname", DbType="VarChar(50)")]
		public string Hostname
		{
			get
			{
				return this._Hostname;
			}
			set
			{
				if ((this._Hostname != value))
				{
					this._Hostname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoId", DbType="Char(2)")]
		public string EstadoId
		{
			get
			{
				return this._EstadoId;
			}
			set
			{
				if ((this._EstadoId != value))
				{
					this._EstadoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCampania", DbType="Char(4)")]
		public string idCampania
		{
			get
			{
				return this._idCampania;
			}
			set
			{
				if ((this._idCampania != value))
				{
					this._idCampania = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPackingList", DbType="VarChar(30)")]
		public string NumeroPackingList
		{
			get
			{
				return this._NumeroPackingList;
			}
			set
			{
				if ((this._NumeroPackingList != value))
				{
					this._NumeroPackingList = value;
				}
			}
		}
	}
	
	public partial class SAS_ListadoConformidadCargaByBookingResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _IdConformacionCarga;
		
		private string _ConformidadCarga;
		
		private string _Booking;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _PackingListId;
		
		private string _NumeroPackingList;
		
		private string _IdRegistroPalletaDistribuido;
		
		private int _UbicacionDelPalletEnContenedor;
		
		private System.Nullable<int> _Fila;
		
		private System.Nullable<int> _Columna;
		
		private string _Termoregistro;
		
		private string _NumeroPaleta;
		
		private string _NumeroManual;
		
		public SAS_ListadoConformidadCargaByBookingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConformacionCarga", DbType="Int")]
		public System.Nullable<int> IdConformacionCarga
		{
			get
			{
				return this._IdConformacionCarga;
			}
			set
			{
				if ((this._IdConformacionCarga != value))
				{
					this._IdConformacionCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConformidadCarga", DbType="VarChar(250)")]
		public string ConformidadCarga
		{
			get
			{
				return this._ConformidadCarga;
			}
			set
			{
				if ((this._ConformidadCarga != value))
				{
					this._ConformidadCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking", DbType="VarChar(20)")]
		public string Booking
		{
			get
			{
				return this._Booking;
			}
			set
			{
				if ((this._Booking != value))
				{
					this._Booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackingListId", DbType="VarChar(16)")]
		public string PackingListId
		{
			get
			{
				return this._PackingListId;
			}
			set
			{
				if ((this._PackingListId != value))
				{
					this._PackingListId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPackingList", DbType="VarChar(30)")]
		public string NumeroPackingList
		{
			get
			{
				return this._NumeroPackingList;
			}
			set
			{
				if ((this._NumeroPackingList != value))
				{
					this._NumeroPackingList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroPalletaDistribuido", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string IdRegistroPalletaDistribuido
		{
			get
			{
				return this._IdRegistroPalletaDistribuido;
			}
			set
			{
				if ((this._IdRegistroPalletaDistribuido != value))
				{
					this._IdRegistroPalletaDistribuido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UbicacionDelPalletEnContenedor", DbType="Int NOT NULL")]
		public int UbicacionDelPalletEnContenedor
		{
			get
			{
				return this._UbicacionDelPalletEnContenedor;
			}
			set
			{
				if ((this._UbicacionDelPalletEnContenedor != value))
				{
					this._UbicacionDelPalletEnContenedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fila", DbType="Int")]
		public System.Nullable<int> Fila
		{
			get
			{
				return this._Fila;
			}
			set
			{
				if ((this._Fila != value))
				{
					this._Fila = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Columna", DbType="Int")]
		public System.Nullable<int> Columna
		{
			get
			{
				return this._Columna;
			}
			set
			{
				if ((this._Columna != value))
				{
					this._Columna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termoregistro", DbType="VarChar(20)")]
		public string Termoregistro
		{
			get
			{
				return this._Termoregistro;
			}
			set
			{
				if ((this._Termoregistro != value))
				{
					this._Termoregistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPaleta", DbType="VarChar(20)")]
		public string NumeroPaleta
		{
			get
			{
				return this._NumeroPaleta;
			}
			set
			{
				if ((this._NumeroPaleta != value))
				{
					this._NumeroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroManual", DbType="VarChar(22)")]
		public string NumeroManual
		{
			get
			{
				return this._NumeroManual;
			}
			set
			{
				if ((this._NumeroManual != value))
				{
					this._NumeroManual = value;
				}
			}
		}
	}
	
	public partial class SAS_ListadoPaletasDisponiblesParaConformacionDeCargaResult
	{
		
		private int _seleccionado;
		
		private string _id;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _IdRegistroPaleta;
		
		private System.Nullable<decimal> _NumeroDeCajas;
		
		private string _IdCampania;
		
		private string _Campania;
		
		private string _paletaOrigen;
		
		private string _ClienteId;
		
		private string _Cliente;
		
		private string _CultivoId;
		
		private string _Cultivo;
		
		private string _VariedadId;
		
		private string _Variedad;
		
		private string _EnvaseId;
		
		private string _Envase;
		
		private string _TipoDePaletaId;
		
		private string _TipoDePaleta;
		
		private string _CategoriaId;
		
		private string _Categoria;
		
		private string _CalibreId;
		
		private string _Calibre;
		
		private string _ColorId;
		
		private string _Color;
		
		private string _Trazabilidad;
		
		private string _EmbalajeId;
		
		private string _Embalaje;
		
		private string _NumeroPaleta;
		
		private System.Nullable<decimal> _PesoReferencial;
		
		private string _GrowerCode;
		
		public SAS_ListadoPaletasDisponiblesParaConformacionDeCargaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seleccionado", DbType="Int NOT NULL")]
		public int seleccionado
		{
			get
			{
				return this._seleccionado;
			}
			set
			{
				if ((this._seleccionado != value))
				{
					this._seleccionado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(15)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroPaleta", DbType="VarChar(15)")]
		public string IdRegistroPaleta
		{
			get
			{
				return this._IdRegistroPaleta;
			}
			set
			{
				if ((this._IdRegistroPaleta != value))
				{
					this._IdRegistroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDeCajas", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> NumeroDeCajas
		{
			get
			{
				return this._NumeroDeCajas;
			}
			set
			{
				if ((this._NumeroDeCajas != value))
				{
					this._NumeroDeCajas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCampania", DbType="Char(4)")]
		public string IdCampania
		{
			get
			{
				return this._IdCampania;
			}
			set
			{
				if ((this._IdCampania != value))
				{
					this._IdCampania = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campania", DbType="VarChar(100)")]
		public string Campania
		{
			get
			{
				return this._Campania;
			}
			set
			{
				if ((this._Campania != value))
				{
					this._Campania = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paletaOrigen", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string paletaOrigen
		{
			get
			{
				return this._paletaOrigen;
			}
			set
			{
				if ((this._paletaOrigen != value))
				{
					this._paletaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteId", DbType="VarChar(11)")]
		public string ClienteId
		{
			get
			{
				return this._ClienteId;
			}
			set
			{
				if ((this._ClienteId != value))
				{
					this._ClienteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(200)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CultivoId", DbType="Char(4)")]
		public string CultivoId
		{
			get
			{
				return this._CultivoId;
			}
			set
			{
				if ((this._CultivoId != value))
				{
					this._CultivoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cultivo", DbType="VarChar(50)")]
		public string Cultivo
		{
			get
			{
				return this._Cultivo;
			}
			set
			{
				if ((this._Cultivo != value))
				{
					this._Cultivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariedadId", DbType="Char(3)")]
		public string VariedadId
		{
			get
			{
				return this._VariedadId;
			}
			set
			{
				if ((this._VariedadId != value))
				{
					this._VariedadId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variedad", DbType="VarChar(80)")]
		public string Variedad
		{
			get
			{
				return this._Variedad;
			}
			set
			{
				if ((this._Variedad != value))
				{
					this._Variedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvaseId", DbType="Char(3)")]
		public string EnvaseId
		{
			get
			{
				return this._EnvaseId;
			}
			set
			{
				if ((this._EnvaseId != value))
				{
					this._EnvaseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Envase", DbType="VarChar(12)")]
		public string Envase
		{
			get
			{
				return this._Envase;
			}
			set
			{
				if ((this._Envase != value))
				{
					this._Envase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaletaId", DbType="Char(3)")]
		public string TipoDePaletaId
		{
			get
			{
				return this._TipoDePaletaId;
			}
			set
			{
				if ((this._TipoDePaletaId != value))
				{
					this._TipoDePaletaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaleta", DbType="VarChar(50)")]
		public string TipoDePaleta
		{
			get
			{
				return this._TipoDePaleta;
			}
			set
			{
				if ((this._TipoDePaleta != value))
				{
					this._TipoDePaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaId", DbType="Char(3)")]
		public string CategoriaId
		{
			get
			{
				return this._CategoriaId;
			}
			set
			{
				if ((this._CategoriaId != value))
				{
					this._CategoriaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(10)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalibreId", DbType="Char(6)")]
		public string CalibreId
		{
			get
			{
				return this._CalibreId;
			}
			set
			{
				if ((this._CalibreId != value))
				{
					this._CalibreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calibre", DbType="VarChar(10)")]
		public string Calibre
		{
			get
			{
				return this._Calibre;
			}
			set
			{
				if ((this._Calibre != value))
				{
					this._Calibre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorId", DbType="VarChar(3)")]
		public string ColorId
		{
			get
			{
				return this._ColorId;
			}
			set
			{
				if ((this._ColorId != value))
				{
					this._ColorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(10)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trazabilidad", DbType="VarChar(8000)")]
		public string Trazabilidad
		{
			get
			{
				return this._Trazabilidad;
			}
			set
			{
				if ((this._Trazabilidad != value))
				{
					this._Trazabilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmbalajeId", DbType="Char(10)")]
		public string EmbalajeId
		{
			get
			{
				return this._EmbalajeId;
			}
			set
			{
				if ((this._EmbalajeId != value))
				{
					this._EmbalajeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Embalaje", DbType="VarChar(20)")]
		public string Embalaje
		{
			get
			{
				return this._Embalaje;
			}
			set
			{
				if ((this._Embalaje != value))
				{
					this._Embalaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPaleta", DbType="VarChar(20)")]
		public string NumeroPaleta
		{
			get
			{
				return this._NumeroPaleta;
			}
			set
			{
				if ((this._NumeroPaleta != value))
				{
					this._NumeroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoReferencial", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> PesoReferencial
		{
			get
			{
				return this._PesoReferencial;
			}
			set
			{
				if ((this._PesoReferencial != value))
				{
					this._PesoReferencial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowerCode", DbType="VarChar(20)")]
		public string GrowerCode
		{
			get
			{
				return this._GrowerCode;
			}
			set
			{
				if ((this._GrowerCode != value))
				{
					this._GrowerCode = value;
				}
			}
		}
	}
	
	public partial class SAS_ListadoConformacionDeCargaPBIByIdResult
	{
		
		private string _EmpresaID;
		
		private string _Empresa;
		
		private System.Nullable<int> _Semana;
		
		private int _ConformacionCargaId;
		
		private System.DateTime _ConformacionCargaFecha;
		
		private string _ConformacionCarga;
		
		private string _NumeroContenedor;
		
		private string _Booking;
		
		private string _NumeroPackingList;
		
		private string _Observacion;
		
		private string _CampaniaId;
		
		private string _EstadoId;
		
		private string _EstadoConformidadCarga;
		
		private string _Campania;
		
		private System.Nullable<int> _Id;
		
		private string _IdRegistroPaleta;
		
		private string _NumeroPaleta;
		
		private string _TipoDePaletaId;
		
		private string _TipoDePaleta;
		
		private string _ClienteId;
		
		private string _Cliente;
		
		private string _GrowerCode;
		
		private System.Nullable<byte> _EstadoDetalle;
		
		private string _CultivoId;
		
		private string _Cultivo;
		
		private string _VariedadId;
		
		private string _Variedad;
		
		private string _EnvaseId;
		
		private string _Envase;
		
		private string _CategoriaId;
		
		private string _Categoria;
		
		private string _CalibreId;
		
		private string _Calibre;
		
		private string _ColorId;
		
		private string _Color;
		
		private string _PahiruelaId;
		
		private string _Pahiruela;
		
		private string _FechaProduccion;
		
		private System.Nullable<decimal> _CantidadCajas;
		
		private string _PaletaOrigen;
		
		private string _traza;
		
		private System.Nullable<decimal> _pesoReferencial;
		
		private string _EmbalajeId;
		
		private string _Embalaje;
		
		public SAS_ListadoConformacionDeCargaPBIByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpresaID", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string EmpresaID
		{
			get
			{
				return this._EmpresaID;
			}
			set
			{
				if ((this._EmpresaID != value))
				{
					this._EmpresaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="VarChar(29) NOT NULL", CanBeNull=false)]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this._Empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semana", DbType="Int")]
		public System.Nullable<int> Semana
		{
			get
			{
				return this._Semana;
			}
			set
			{
				if ((this._Semana != value))
				{
					this._Semana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConformacionCargaId", DbType="Int NOT NULL")]
		public int ConformacionCargaId
		{
			get
			{
				return this._ConformacionCargaId;
			}
			set
			{
				if ((this._ConformacionCargaId != value))
				{
					this._ConformacionCargaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConformacionCargaFecha", DbType="SmallDateTime NOT NULL")]
		public System.DateTime ConformacionCargaFecha
		{
			get
			{
				return this._ConformacionCargaFecha;
			}
			set
			{
				if ((this._ConformacionCargaFecha != value))
				{
					this._ConformacionCargaFecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConformacionCarga", DbType="VarChar(250)")]
		public string ConformacionCarga
		{
			get
			{
				return this._ConformacionCarga;
			}
			set
			{
				if ((this._ConformacionCarga != value))
				{
					this._ConformacionCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroContenedor", DbType="VarChar(20)")]
		public string NumeroContenedor
		{
			get
			{
				return this._NumeroContenedor;
			}
			set
			{
				if ((this._NumeroContenedor != value))
				{
					this._NumeroContenedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Booking", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Booking
		{
			get
			{
				return this._Booking;
			}
			set
			{
				if ((this._Booking != value))
				{
					this._Booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPackingList", DbType="VarChar(30)")]
		public string NumeroPackingList
		{
			get
			{
				return this._NumeroPackingList;
			}
			set
			{
				if ((this._NumeroPackingList != value))
				{
					this._NumeroPackingList = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(500)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CampaniaId", DbType="Char(4)")]
		public string CampaniaId
		{
			get
			{
				return this._CampaniaId;
			}
			set
			{
				if ((this._CampaniaId != value))
				{
					this._CampaniaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoId", DbType="Char(2)")]
		public string EstadoId
		{
			get
			{
				return this._EstadoId;
			}
			set
			{
				if ((this._EstadoId != value))
				{
					this._EstadoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoConformidadCarga", DbType="VarChar(30)")]
		public string EstadoConformidadCarga
		{
			get
			{
				return this._EstadoConformidadCarga;
			}
			set
			{
				if ((this._EstadoConformidadCarga != value))
				{
					this._EstadoConformidadCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campania", DbType="VarChar(100)")]
		public string Campania
		{
			get
			{
				return this._Campania;
			}
			set
			{
				if ((this._Campania != value))
				{
					this._Campania = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroPaleta", DbType="VarChar(19)")]
		public string IdRegistroPaleta
		{
			get
			{
				return this._IdRegistroPaleta;
			}
			set
			{
				if ((this._IdRegistroPaleta != value))
				{
					this._IdRegistroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPaleta", DbType="VarChar(20)")]
		public string NumeroPaleta
		{
			get
			{
				return this._NumeroPaleta;
			}
			set
			{
				if ((this._NumeroPaleta != value))
				{
					this._NumeroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaletaId", DbType="Char(3)")]
		public string TipoDePaletaId
		{
			get
			{
				return this._TipoDePaletaId;
			}
			set
			{
				if ((this._TipoDePaletaId != value))
				{
					this._TipoDePaletaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaleta", DbType="VarChar(50)")]
		public string TipoDePaleta
		{
			get
			{
				return this._TipoDePaleta;
			}
			set
			{
				if ((this._TipoDePaleta != value))
				{
					this._TipoDePaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteId", DbType="VarChar(14)")]
		public string ClienteId
		{
			get
			{
				return this._ClienteId;
			}
			set
			{
				if ((this._ClienteId != value))
				{
					this._ClienteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(200)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowerCode", DbType="VarChar(8000)")]
		public string GrowerCode
		{
			get
			{
				return this._GrowerCode;
			}
			set
			{
				if ((this._GrowerCode != value))
				{
					this._GrowerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoDetalle", DbType="TinyInt")]
		public System.Nullable<byte> EstadoDetalle
		{
			get
			{
				return this._EstadoDetalle;
			}
			set
			{
				if ((this._EstadoDetalle != value))
				{
					this._EstadoDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CultivoId", DbType="Char(4)")]
		public string CultivoId
		{
			get
			{
				return this._CultivoId;
			}
			set
			{
				if ((this._CultivoId != value))
				{
					this._CultivoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cultivo", DbType="VarChar(50)")]
		public string Cultivo
		{
			get
			{
				return this._Cultivo;
			}
			set
			{
				if ((this._Cultivo != value))
				{
					this._Cultivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariedadId", DbType="Char(3)")]
		public string VariedadId
		{
			get
			{
				return this._VariedadId;
			}
			set
			{
				if ((this._VariedadId != value))
				{
					this._VariedadId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variedad", DbType="VarChar(80)")]
		public string Variedad
		{
			get
			{
				return this._Variedad;
			}
			set
			{
				if ((this._Variedad != value))
				{
					this._Variedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvaseId", DbType="Char(3)")]
		public string EnvaseId
		{
			get
			{
				return this._EnvaseId;
			}
			set
			{
				if ((this._EnvaseId != value))
				{
					this._EnvaseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Envase", DbType="VarChar(12)")]
		public string Envase
		{
			get
			{
				return this._Envase;
			}
			set
			{
				if ((this._Envase != value))
				{
					this._Envase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaId", DbType="Char(3)")]
		public string CategoriaId
		{
			get
			{
				return this._CategoriaId;
			}
			set
			{
				if ((this._CategoriaId != value))
				{
					this._CategoriaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(10)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalibreId", DbType="Char(6)")]
		public string CalibreId
		{
			get
			{
				return this._CalibreId;
			}
			set
			{
				if ((this._CalibreId != value))
				{
					this._CalibreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calibre", DbType="VarChar(10)")]
		public string Calibre
		{
			get
			{
				return this._Calibre;
			}
			set
			{
				if ((this._Calibre != value))
				{
					this._Calibre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorId", DbType="VarChar(3)")]
		public string ColorId
		{
			get
			{
				return this._ColorId;
			}
			set
			{
				if ((this._ColorId != value))
				{
					this._ColorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(10)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PahiruelaId", DbType="VarChar(3)")]
		public string PahiruelaId
		{
			get
			{
				return this._PahiruelaId;
			}
			set
			{
				if ((this._PahiruelaId != value))
				{
					this._PahiruelaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pahiruela", DbType="VarChar(100)")]
		public string Pahiruela
		{
			get
			{
				return this._Pahiruela;
			}
			set
			{
				if ((this._Pahiruela != value))
				{
					this._Pahiruela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProduccion", DbType="VarChar(8000)")]
		public string FechaProduccion
		{
			get
			{
				return this._FechaProduccion;
			}
			set
			{
				if ((this._FechaProduccion != value))
				{
					this._FechaProduccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadCajas", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CantidadCajas
		{
			get
			{
				return this._CantidadCajas;
			}
			set
			{
				if ((this._CantidadCajas != value))
				{
					this._CantidadCajas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaletaOrigen", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string PaletaOrigen
		{
			get
			{
				return this._PaletaOrigen;
			}
			set
			{
				if ((this._PaletaOrigen != value))
				{
					this._PaletaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_traza", DbType="VarChar(8000)")]
		public string traza
		{
			get
			{
				return this._traza;
			}
			set
			{
				if ((this._traza != value))
				{
					this._traza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoReferencial", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> pesoReferencial
		{
			get
			{
				return this._pesoReferencial;
			}
			set
			{
				if ((this._pesoReferencial != value))
				{
					this._pesoReferencial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmbalajeId", DbType="Char(10)")]
		public string EmbalajeId
		{
			get
			{
				return this._EmbalajeId;
			}
			set
			{
				if ((this._EmbalajeId != value))
				{
					this._EmbalajeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Embalaje", DbType="VarChar(20)")]
		public string Embalaje
		{
			get
			{
				return this._Embalaje;
			}
			set
			{
				if ((this._Embalaje != value))
				{
					this._Embalaje = value;
				}
			}
		}
	}
	
	public partial class SAS_ListadoConformacionDeCargaDisponiblesByIdClienteResult
	{
		
		private int _selecionado;
		
		private string _IdRegistroPaleta;
		
		private string _NumeroPaleta;
		
		private string _TipoDePaletaId;
		
		private string _TipoDePaleta;
		
		private string _ClienteId;
		
		private string _Cliente;
		
		private string _GrowerCode;
		
		private string _CultivoId;
		
		private string _Cultivo;
		
		private string _VariedadId;
		
		private string _Variedad;
		
		private string _EnvaseId;
		
		private string _Envase;
		
		private string _CategoriaId;
		
		private string _Categoria;
		
		private string _CalibreId;
		
		private string _Calibre;
		
		private string _ColorId;
		
		private string _Color;
		
		private string _EmbalajeId;
		
		private string _Embalaje;
		
		private string _PahiruelaId;
		
		private string _Pahiruela;
		
		private string _FechaProduccion;
		
		private System.Nullable<decimal> _NumeroDeCajas;
		
		private string _paletaOrigen;
		
		private string _Trazabilidad;
		
		private string _Semana;
		
		private string _PeriodoSemana;
		
		private string _item;
		
		private System.Nullable<decimal> _PesoReferencial;
		
		private string _IdCampania;
		
		public SAS_ListadoConformacionDeCargaDisponiblesByIdClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selecionado", DbType="Int NOT NULL")]
		public int selecionado
		{
			get
			{
				return this._selecionado;
			}
			set
			{
				if ((this._selecionado != value))
				{
					this._selecionado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistroPaleta", DbType="VarChar(15)")]
		public string IdRegistroPaleta
		{
			get
			{
				return this._IdRegistroPaleta;
			}
			set
			{
				if ((this._IdRegistroPaleta != value))
				{
					this._IdRegistroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPaleta", DbType="VarChar(20)")]
		public string NumeroPaleta
		{
			get
			{
				return this._NumeroPaleta;
			}
			set
			{
				if ((this._NumeroPaleta != value))
				{
					this._NumeroPaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaletaId", DbType="Char(3)")]
		public string TipoDePaletaId
		{
			get
			{
				return this._TipoDePaletaId;
			}
			set
			{
				if ((this._TipoDePaletaId != value))
				{
					this._TipoDePaletaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePaleta", DbType="VarChar(50)")]
		public string TipoDePaleta
		{
			get
			{
				return this._TipoDePaleta;
			}
			set
			{
				if ((this._TipoDePaleta != value))
				{
					this._TipoDePaleta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteId", DbType="VarChar(11)")]
		public string ClienteId
		{
			get
			{
				return this._ClienteId;
			}
			set
			{
				if ((this._ClienteId != value))
				{
					this._ClienteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(200)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowerCode", DbType="VarChar(20)")]
		public string GrowerCode
		{
			get
			{
				return this._GrowerCode;
			}
			set
			{
				if ((this._GrowerCode != value))
				{
					this._GrowerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CultivoId", DbType="Char(4)")]
		public string CultivoId
		{
			get
			{
				return this._CultivoId;
			}
			set
			{
				if ((this._CultivoId != value))
				{
					this._CultivoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cultivo", DbType="VarChar(50)")]
		public string Cultivo
		{
			get
			{
				return this._Cultivo;
			}
			set
			{
				if ((this._Cultivo != value))
				{
					this._Cultivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariedadId", DbType="Char(3)")]
		public string VariedadId
		{
			get
			{
				return this._VariedadId;
			}
			set
			{
				if ((this._VariedadId != value))
				{
					this._VariedadId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variedad", DbType="VarChar(80)")]
		public string Variedad
		{
			get
			{
				return this._Variedad;
			}
			set
			{
				if ((this._Variedad != value))
				{
					this._Variedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnvaseId", DbType="Char(3)")]
		public string EnvaseId
		{
			get
			{
				return this._EnvaseId;
			}
			set
			{
				if ((this._EnvaseId != value))
				{
					this._EnvaseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Envase", DbType="VarChar(12)")]
		public string Envase
		{
			get
			{
				return this._Envase;
			}
			set
			{
				if ((this._Envase != value))
				{
					this._Envase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoriaId", DbType="Char(3)")]
		public string CategoriaId
		{
			get
			{
				return this._CategoriaId;
			}
			set
			{
				if ((this._CategoriaId != value))
				{
					this._CategoriaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(10)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalibreId", DbType="Char(6)")]
		public string CalibreId
		{
			get
			{
				return this._CalibreId;
			}
			set
			{
				if ((this._CalibreId != value))
				{
					this._CalibreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calibre", DbType="VarChar(10)")]
		public string Calibre
		{
			get
			{
				return this._Calibre;
			}
			set
			{
				if ((this._Calibre != value))
				{
					this._Calibre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorId", DbType="VarChar(3)")]
		public string ColorId
		{
			get
			{
				return this._ColorId;
			}
			set
			{
				if ((this._ColorId != value))
				{
					this._ColorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(10)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this._Color = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmbalajeId", DbType="Char(10)")]
		public string EmbalajeId
		{
			get
			{
				return this._EmbalajeId;
			}
			set
			{
				if ((this._EmbalajeId != value))
				{
					this._EmbalajeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Embalaje", DbType="VarChar(20)")]
		public string Embalaje
		{
			get
			{
				return this._Embalaje;
			}
			set
			{
				if ((this._Embalaje != value))
				{
					this._Embalaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PahiruelaId", DbType="VarChar(3)")]
		public string PahiruelaId
		{
			get
			{
				return this._PahiruelaId;
			}
			set
			{
				if ((this._PahiruelaId != value))
				{
					this._PahiruelaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pahiruela", DbType="VarChar(100)")]
		public string Pahiruela
		{
			get
			{
				return this._Pahiruela;
			}
			set
			{
				if ((this._Pahiruela != value))
				{
					this._Pahiruela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProduccion", DbType="VarChar(8000)")]
		public string FechaProduccion
		{
			get
			{
				return this._FechaProduccion;
			}
			set
			{
				if ((this._FechaProduccion != value))
				{
					this._FechaProduccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDeCajas", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> NumeroDeCajas
		{
			get
			{
				return this._NumeroDeCajas;
			}
			set
			{
				if ((this._NumeroDeCajas != value))
				{
					this._NumeroDeCajas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paletaOrigen", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string paletaOrigen
		{
			get
			{
				return this._paletaOrigen;
			}
			set
			{
				if ((this._paletaOrigen != value))
				{
					this._paletaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trazabilidad", DbType="VarChar(8000)")]
		public string Trazabilidad
		{
			get
			{
				return this._Trazabilidad;
			}
			set
			{
				if ((this._Trazabilidad != value))
				{
					this._Trazabilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semana", DbType="VarChar(3)")]
		public string Semana
		{
			get
			{
				return this._Semana;
			}
			set
			{
				if ((this._Semana != value))
				{
					this._Semana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoSemana", DbType="VarChar(8)")]
		public string PeriodoSemana
		{
			get
			{
				return this._PeriodoSemana;
			}
			set
			{
				if ((this._PeriodoSemana != value))
				{
					this._PeriodoSemana = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item", DbType="VarChar(8000)")]
		public string item
		{
			get
			{
				return this._item;
			}
			set
			{
				if ((this._item != value))
				{
					this._item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PesoReferencial", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> PesoReferencial
		{
			get
			{
				return this._PesoReferencial;
			}
			set
			{
				if ((this._PesoReferencial != value))
				{
					this._PesoReferencial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCampania", DbType="Char(4)")]
		public string IdCampania
		{
			get
			{
				return this._IdCampania;
			}
			set
			{
				if ((this._IdCampania != value))
				{
					this._IdCampania = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
